### ISSUE TITLE
Force compiler versions

### ISSUE THREAD

**Issue by coppolachan** [paboyle/Grid#103]
Suggestion:
we can include another header (like compiler_checks.h) with these lines to check that the compilers are satisfying the minimal reqs

```
// exclude unsupported compilers
#if defined(__clang__)
    #define CLANG_VERSION (__clang_major__ * 10000 + __clang_minor__ * 100 + __clang_patchlevel__)
    #if CLANG_VERSION < 30400
        #error "unsupported Clang version"
    #endif
#elif defined(__GNUC__)
    #define GCC_VERSION (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__)
    #if GCC_VERSION < 40800
        #error "unsupported GCC version"
    #endif
#endif

```

**Comment by paboyle** [comment]
So you agree we rule out
gcc 5.0; 5.1; 5.2; 5.3; 5.4 ; 6.0; 6.1; 6.2 ?

**Comment by paboyle** [comment]
I want Guido and Antonin's opinion on this ruling out bad GCC versions?

**Comment by aportelli** [comment]
I would say rule them out for now. I want to work on it, it is not excluded that there is a simple way to avoid to problematic unions. Let us keep this issue open and I’ll report here, in case of success we can reopen these versions in a hotfix.

**Comment by coppolachan** [comment]
No ruling out, this will exclude perfectly working code in the Cambridge HPCS machine right now): 
big warning at configure/compile time that some things could not work properly due to the compiler (link to the issue)

**Comment by paboyle** [comment]
So warning and noisy compile  on GCC 5/6 ?

**Comment by paboyle** [comment]
Closing; this really should be joined with issue 100, as the last issue for 0.7.0

**Comment by coppolachan** [comment]
Agree on the noisy compile and joining to 100.
But we should put a lower boundary (gcc 4.8? clang?), that was the original intent of filing issue.

**Comment by paboyle** [comment]
closing. This duplicates 100 and will answer there.
