### ISSUE TITLE
Compiler warnings for GCC (Eigen)

### ISSUE THREAD

**Issue by coppolachan** [paboyle/Grid#104]
GCC throws a lot of the following harmless warnings, coming from the Eigen lib
```
                 from /home/dc-coss2/Codes/RMHMC/Stealth-Grid/include/Grid/Eigen/Dense:1,
                 from /home/dc-coss2/Codes/RMHMC/Stealth-Grid/include/Grid/lattice/Lattice_reduction.h:25,
                 from /home/dc-coss2/Codes/RMHMC/Stealth-Grid/include/Grid/lattice/Lattice_base.h:339,
                 from /home/dc-coss2/Codes/RMHMC/Stealth-Grid/include/Grid/lattice/Lattice.h:31,
                 from /home/dc-coss2/Codes/RMHMC/Stealth-Grid/include/Grid/GridCore.h:54,
                 from /home/dc-coss2/Codes/RMHMC/Stealth-Grid/include/Grid/Grid.h:41,
                 from ../../Stealth-Grid/lib/qcd/spin/Gamma.cc:3:
/home/dc-coss2/Codes/RMHMC/Stealth-Grid/include/Grid/Eigen/src/Core/Functors.h:977:28: warning: ‘template<class _Operation> class std::binder1st’ is deprecated [-Wdeprecated-declarations]
 struct functor_traits<std::binder1st<T> >
```

should we suppress them or look for a newer version of the Eigen that solves this?

**Comment by paboyle** [comment]
Updating Eigen would be best, clearly. As you know I hate warning suppression and would rather just have legal code, even though this is strictly a deprecated warning and GCC is being a bit naughty (in the sense that verbose warning on constructs still supported but planned for deprecation is a pain in the ass pedant thing to do).

**Comment by aportelli** [comment]
I agree, especially that Eigen has been going through several versions since. New versions does support AVX512. In principle just the URL in the Eigen script should be changed.

**Comment by paboyle** [comment]
updated to 3.3.3

**Comment by coppolachan** [comment]
is the problem solved with the update?

**Comment by paboyle** [comment]
Was on my laptop; I'm waiting for travis to verify and close.

**Comment by paboyle** [comment]
Compiled clean closing.
