### ISSUE TITLE
Update documentation pages

### ISSUE THREAD

**Issue by coppolachan** [paboyle/Grid#105]
- [ ] Before release 0.7.0 update the https://paboyle.github.io/Grid/ pages

**Comment by paboyle** [comment]
What are you going to update and what is the time frame?

**Comment by coppolachan** [comment]
This week, max Monday? Updating these pages https://paboyle.github.io/Grid/ to reflect the readme + the info about the hmc + anything you or Antonin want to add on the usage of Grid

**Comment by paboyle** [comment]
Those pages don't have a version tag on them. What branch are they reflecting?

**Comment by aportelli** [comment]
Are we ready to commit on documentation for 0.7? I would imagine an update of the README is enough for now and we could schedule doc for 0.8.

**Comment by coppolachan** [comment]
Branch gh-pages

**Comment by paboyle** [comment]
Absolutely agree Antonin. In any case, the 0.7 and master are not the branch that is displayed so the pages can be updated later and there is no reason to have that delay our collaborators from getting 0.7 into production.

**Comment by coppolachan** [comment]
Cleared from the 0.7.0
I will update anyway in that time frame
