### ISSUE TITLE
BGQ support

### ISSUE THREAD

**Issue by paboyle** [paboyle/Grid#106]
Must revisit the BG/Q now and verify current release against it.
Plan BG/Q addition to KNL for good performance in v0.8. Possibly a v0.7.1 intermediate release if 0.8 milestones are going to be a long time.

**Comment by paboyle** [comment]
Andrew's tests clearly indicate BG/Q regression issues as merely not matching Boundary Conditions
in the UKhadron / Grid comparison correctly. Makes BG/Q resurrection easier as we just need to make sure the BG/Q code passes self tests. (Assuming when Andrew gets a chance he matches the solutions to DWF with the right BC's in the comparison... and that this is successful which is not *yet* guaranteed but would be "surprised" if it fails.).

**Comment by aportelli** [comment]
Andrew (@Lanny91) could you please give us some summary about the current status of tests you did on the BG/Q?

**Comment by Lanny91** [comment]
Sure, I cross-checked all the non-stochastic correlators we need for the rare kaon decay project against UKhadron. So the meson & weak contractions, with and without momentum, with point and wall sources. I ran on the test queue, so 128 nodes, 32 threads per node. With unit gauge and on a 16^3x32 SU3 configuration I find complete agreement between Grid and UKhadron up to 6 significant figures - which is the maximum precision that I get from the XML output of Grid.

**Comment by aportelli** [comment]
Wow that sounds fantastic, 

For the check an HDF5 input would be more precise, I painfully managed to compile HDF5 for BG/Q and Grid works with it. My configure line was
```
../../configure --enable-precision=double --enable-comms=mpi-auto --enable-simd=BGQ --with-hdf5=/dirac2/work/dp008/dp008/dc-port1/Grid/clang_BGQ_double_mpi --prefix=/dirac2/work/dp008/dp008/dc-port1/Grid/clang_BGQ_double_mpi CXX=bgclang++ CXXFLAGS=-g -Wno-format MPICXX=mpiclang++
```
you should be able to get and use my HDF5 build from that. Use the `h5dump` command to read the results, there are options to increase the precision of what's displayed.

Some summary of the performances vs. UKHadron/BFM would be very interesting.

**Comment by aportelli** [comment]
Christoph (@lehner) you were asking me in Chicago, this is the status.

**Comment by lehner** [comment]
Thanks!

**Comment by paboyle** [comment]
the XML precision should be possible to improve. I've been worrying a bit about whether
we should try to take control of the field width and precision in XML output.

**Comment by paboyle** [comment]
Hi Andrew 
-- Did you check the assembly code  (--dslash-asm)
-- Comms overlap with compute (--comms-overlap)
-- Performance ?
Thanks,
Peter

**Comment by Lanny91** [comment]
The assembly code works fine, however if I enable --comms-overlap I hit an assert as `AsmDhopSiteInt` and `AsmDhopSiteExt` have not been implemented for QPX.

I checked performance briefly, but it is still heavily comms-limited running on the test queue. e.g. a 8^4 local volume reaches ~51 Gflops without comms, ~22 Gflops with comms.

**Comment by paboyle** [comment]
Thanks -- exactly the sort of information I'm looking for.

Will look into it, realistically tail end of the week since I'm both travelling and doing boatloads of paperwork this week. :(

**Comment by paboyle** [comment]
Bit sad, but closing.
