### ISSUE TITLE
Doxygen?

### ISSUE THREAD

**Issue by coppolachan** [paboyle/Grid#11]
What is the point of view of the developers on starting to write the doxygen annotations before the code becomes too big?
Any other suggestion about the documentation?

**Comment by paboyle** [comment]
Personally, I don't like Doxy tagging; it's the sort of thing that doubles the edit work when changing
something and repeating the parameters of a function in comments is just torture for me.

The result is that the tags are always less well maintained than the code, so out of date or missing
and I prefer to not doxy tag and simply aim for maximum clarity and readability in the code.

I think that an API definition document is smart, something in latex that is written in the style of the
present QDP++ manual makes sense. Defining how the code is supposed to behave in a way that
is not simply saying "it is the current implementation" is wise. One of the things on the "TODO" list as far as I recall. Certainly something I have promised to do for RBC.

**Comment by mspraggs** [comment]
I'm strongly in favour of this. The QDP++ manual is an invaluable introduction to the overall structure and design of the package, which is something that is impossible to gain by simply reading the code, and hence essential to newcomers.

**Comment by coppolachan** [comment]
A good manual is really important for the final user that want to start learning the code. No doubt, and we should definitely write.
About doxygen: I found it really useful to navigate a big code, because the definition and use of classes, variables, methods, can be scattered around.  Doxygen provides the tree view, the automatic links and several other things useful to quickly jump among files/definitions. Chroma without doxygen is a nightmare to learn.

**Comment by coppolachan** [comment]
I rebump this since documentation is becoming necessary. 
I remain of the view that an automatic, surfable, documentation of the code is necessary together with a thorough description a la QDP++ (which has the same issue of being up-to-date since depends on us anyway). Especially since we have so many templated classes that really needs navigation in the code to understand the full structure.

**Comment by aportelli** [comment]
Just wondering about this issue considering an soonish 0.6 release. Is Doxygen generation working, is there anything to do here?

**Comment by paboyle** [comment]
we have to make sure doxygen is optional, since not every system will have doxygen
so, adding a configure flag --enable-doxygen to build the html is the best option, with a default of "off".

**Comment by coppolachan** [comment]
agree on it being optional with a flag.

Doxygen generation has not been tested but it should work as most of the code is just c++.
At least gives the surfable, uncommented, html.

**Comment by aportelli** [comment]
I can take care of that.

**Comment by aportelli** [comment]
Hi Guido,
I managed to create something a bit nicer with Doxygen. You can now use `--enable-doxygen-doc` with` configure to enable the HTML doc. Then `make doxygen-doc` build the doc. I have put that in `feature/doxygen`. Could you see if it is ok for you and merge it back to `develop` when everything is ok?

**Comment by coppolachan** [comment]
Ok, let me check. Not immediately as I'm concentrating on the hirep stuff, but in time for the 0.6 release.

**Comment by aportelli** [comment]
Hi Guido could you please check that the new build options for Doxygen are good for you in `feature/doxygen` so that I can merge it back to `develop`?

**Comment by coppolachan** [comment]
Few things that are not clear (compiling with clang, I have dot and doxygen in my path)

How to compile to get just the html? --enable-doxygen does not seem to work and the configure --help does not say much. 

I tried --enable-doxygen-dot and --enable-doxygen-pdf too and in both cases it complains with an error like this in the config.log 
configure:8020: error: doxygen-pdf requires doxygen-pdf

**Comment by aportelli** [comment]
Have you tried `--enable-doxygen-doc` as in my original instructions?

**Comment by coppolachan** [comment]
ok thanks, looks working. 
Minor thing: if I modify a file the make doxygen-doc does not recognise the modification and insists that the html is up to date. 

I think you can move to the develop at this stage anyway.

**Comment by aportelli** [comment]
Hi Guido I missed that for 0.6, I will merge it with `develop` and close the issue.
