### ISSUE TITLE
Serialisation "grid" top level in XML format

### ISSUE THREAD

**Issue by paboyle** [paboyle/Grid#113]
The XmlWriter class inserts an outer "grid" at the top level.

This prevents me from matching Ildg record formats with an XML serialisation and seems
a completely unnecessary. I will eradicate it.

**Comment by aportelli** [comment]
This is not unnecessary, but part of the XML standard https://en.wikipedia.org/wiki/Root_element to have a unique root. I am not sure what's the hold up with ILDG but many XML parsers will throw errors (as they should) will being asked to parse a multi-root document.

**Comment by aportelli** [comment]
One other thing is that the name of the root element is supposed to be completely irrelevant, hence my choice for simply "grid" for us to remember which program generated the XML. Could you explain more what you are exactly trying to do with ILDG? I imagine that their XML also do have a unique root.

**Comment by paboyle** [comment]
Can you clarify -- You understand the root name tag as not being checked or visible?

ILDG specifies an XML segment as follows:

<?xml version="1.0" encoding="UTF-8"?>
     <ildgFormat>
       <version> 1.0 </version>
       <field> su3gauge </field>
       <precision> 32 </precision>
       <lx> 20 </lx> <ly> 20 </ly> <lz> 20 </lz> <lt> 64 </lt>
  </ildgFormat>

I want to obtain it by serialising an object designed to match these:

struct ildgFormat : Serializable {
public:
  GRID_SERIALIZABLE_CLASS_MEMBERS(ildgFormat,
                                  double, version,
                                  std::string, field,
                                  int, precision,
                                  int, lx,
                                  int, ly,
                                  int, lz,
                                  int, lt);
  ildgFormat() {
    version=1.0;
  };
};

One way to encapsulate the difference is to make the "<grid>" optional, perhaps a string argument
with default parameter std::string("grid"), but when set to "" triggering the change.

Clearly, you can only serialise one object if you don't wrap in an outer tag.

**Comment by paboyle** [comment]
For more clarity, way proposed to leave default behaviour unmodified while
still allowing what I need for these XML snippet manipulations.

Test_serialisation.cc:
  { 
    ildgFormat format;
    format.version   =1.0;
    format.field     =std::string("su3gauge");
    format.precision =32;
    format.lx        =24;
    format.ly        =24;
    format.lz        =24;
    format.lt        =48;
//    XmlWriter WR("ildg-format.xml"); // Default param sets named tag "grid" for toplev
    XmlWriter WR("ildg-format.xml",""); // No named tag for toplev
    XmlWriter WRs("","");                         // No file written, no named tag for toplev
    write(WR,"ildgFormat",format);
    write(WRs,"ildgFormat",format);
    std::cout << " XmlString: " <<WRs.XmlString()<<std::endl;
  }
-----------
<?xml version="1.0"?>
<ildgFormat>
	<version>1</version>
	<field>su3gauge</field>
	<precision>32</precision>
	<lx>24</lx>
	<ly>24</ly>
	<lz>24</lz>
	<lt>48</lt>
</ildgFormat>

**Comment by paboyle** [comment]
drat the XML above got formatted automatically
```

"  XmlString: <?xml version="1.0"?>
<ildgFormat>
	<version>1</version>
	<field>su3gauge</field>
	<precision>32</precision>
	<lx>24</lx>
	<ly>24</ly>
	<lz>24</lz>
	<lt>48</lt>
</ildgFormat>
 "
```

**Comment by aportelli** [comment]
Ok thanks for the details, the Grid implementation assume that an object would not be the root node because structured types will always be encapsulated in a node with their name. Because there can be only one root node, doing otherwise would prevent somebody to store several objects in the same XML.

However, your example is perfectly legit and I agree it is not satisfying that this is not working out of the box. An idea would be:

- Keep `XmlWriter` as it is. If we want to allow several objects to be written then we need an additional root node. You could argue that everything could always be encapsulated in a structured type but I think this is a big constraint. It means that the XML structure has to be entirely fixed at compile-time, doing so would certainly break hardly the current way Hadrons XML interface works (module parameters depend on the module type which cannot be predicted in advance).
- `XmlReader` will not read anything if the root node is not "grid". Generally (although I cannot be sure what the standard is) this is supposed to be free, at least that is what I have seen in many parsers. We can keep it that way or not, I am happy with both.
- I can implement new functions `XmlReadObject/XmlWriteObject(T &object, const std::string filename)` that will perform XML I/O for a single object, making the root node of the file the root node of the object. This would cover your case.

Let me know what you think.

**Comment by paboyle** [comment]
I've put in a constructor modification as above, but I'm happy with new functions too. Would
suggest I finish the ILDG I/O on feature/parallelIO first, and once done & working we can revisit
the single object IO to make clean.

Agree there are definitely two cases: single structured object (which was a big constraint in UKhadron's macro system) or multi object, and that these are both sensible in different circumstances and make it necessary to cover cases.

**Comment by aportelli** [comment]
Cool, sounds good to me :-)

**Comment by paboyle** [comment]
I've committed branch back to develop. 

Can read all of SciDAC standard XML snippets this way
(scidac-private-file-xml)
(scidac-private-record-xml)
(scidac-checksum)
scidac-record-xml: usqcdInfo [ gauge field], usqcdPropInfo etc...
ILDG Xml, LFN records.

GridLimeReader/Writer classes.

- open, close

READER
-  template<class vobj> void readLimeLatticeBinaryObject(Lattice<vobj> &,std::string recname)
-   template<class serialisable_object>
    void readLimeObject(serialisable_object &obj,std::string objname,std::string recname)

WRITER
  template<class serialisable_object>  void writeLimeObject(int MB,int ME,serialisable_object &object,std::string object_name,std::string record_name)
  template<class vobj>
  void writeLimeLatticeBinaryObject(Lattice<vobj> &field,std::string record_name)

class ScidacWriter : public GridLimeWriter 
   template<class SerialisableUserFile>
   void writeScidacFileRecord(GridBase *grid,SerialisableUserFile &_userFile)
   template <class vobj, class userRecord> 
   void writeScidacFieldRecord(Lattice<vobj> &field,userRecord _userRecord) 
 

[ ScidacReader not done yet ] 

IldgReader/Writer classes:

  template <class vsimd>
  void writeConfiguration(Lattice<iLorentzColourMatrix<vsimd> > &Umu,int sequence,std::string LFN,std::string description) 

  template <class vsimd>
  void readConfiguration(Lattice<iLorentzColourMatrix<vsimd> > &Umu, FieldMetaData &FieldMetaData_) {

The configuration reader looks for records and checks for those with standardised structures,
in a descending trust hierarchy:

-- grid-format
-- scidac-checksum
-- scidac-private-file-xml
-- scidac-private-record-xml
-- scidac-record-xml (if it contains the string "usqcdInfo" )
-- ildg-format
-- ildg-lfn

Checksum's checked if present; 
Plaquettes checked if present

etc...

It should be easy now to do multi record Scidac files for eigenvectors with good performance.

I abused the Scidac record "datatype" fields (docs have cases:) to introduce new Grid strings with automatic name creation.

From: http://www.physics.utah.edu/~detar/scidac/qio_2p3.pdf

"The datatype string is not interpreted by QIO. It allows the applications programmer a standard way to identify the data type. For that purpose the name should be unique. For that purpose the name should be unique. For QDP/C we use the datatype name of the QDP field. For USQCD standard formats, there are special names. For global data we use the name of one of the QLA datatypes."

and:

"The data type string is USQCD_F3_ColorMatrix, a synonym for QDP_F3_ColorMatrix in older formats, or USQCD_D3_ColorMatrix for double precision." The Lorentz index is noted by a "count = 4".

and

"USQCD_F3_DiracFermion" or "USQCD_D3_DiracFermion"

I don't like this very much. Why is Nc stuck on the precision attribute? As it is an ad hoc laundry list of cases approach, and since it appears that unique names are ok, **I've written and systematically used a generic tensor -> string name mapper** 

   std::stringstream stream;
   stream << "GRID_";
   stream << ScidacWordMnemonic<stype>();

   if ( _LorentzVector )   stream << "_LorentzVector"<<_LorentzN;
   if ( _LorentzMatrix )   stream << "_LorentzMatrix"<<_LorentzN;

   if ( _SpinVector )   stream << "_SpinVector"<<_SpinN;
   if ( _SpinMatrix )   stream << "_SpinMatrix"<<_SpinN;

   if ( _ColourVector )   stream << "_ColourVector"<<_ColourN;
   if ( _ColourMatrix )   stream << "_ColourMatrix"<<_ColourN;

   if ( _ColourScalar && _LorentzScalar && _SpinScalar )   stream << "_Complex";


 Giving type strings denoting the complete tensor structure in a systematic way like 

  GRID_Complex
  GRID_D_SpinVector4_ColourVector3_Complex
  GRID_D_SpinMatrix4_ColourMatrix3_Complex
  GRID_D_LorentzVector4_ColourMatrix3_Complex

 I had to add tensor structure trait query functionality (useful addition anyway):

 rank= indexRank<LorentzIndex>(field);
 scal= isScalar<LorentzIndex>(field);
 vec= isVector<LorentzIndex>(field);
 mat= isMatrix<LorentzIndex>(field);

Perhaps even more contentious, the "S" and "I" 32bit integer or mixed int/float is something I loathe.
I used non-scidac naming for non-floating point as follows:

 template<class word> inline std::string ScidacWordMnemonic(void){ return std::string("unknown"); }
 template<> inline std::string ScidacWordMnemonic<double>  (void){ return std::string("D"); }
 template<> inline std::string ScidacWordMnemonic<float>   (void){ return std::string("F"); }
 template<> inline std::string ScidacWordMnemonic< int32_t>(void){ return std::string("I32"); }
 template<> inline std::string ScidacWordMnemonic<uint32_t>(void){ return std::string("U32"); }
 template<> inline std::string ScidacWordMnemonic< int64_t>(void){ return std::string("I64"); }
 template<> inline std::string ScidacWordMnemonic<uint64_t>(void){ return std::string("U64"); }

Thoughts on all this are welcome.

**Comment by paboyle** [comment]
Closing now as I think we are pretty much done
