### ISSUE TITLE
Runtime errors of tests on Intel SSE4

### ISSUE THREAD

**Issue by nmeyer-ur** [paboyle/Grid#115]
Hi,

during ARM NEON intrinsics layer development I discovered several errors in the Grid benchmarks and tests which occur independent of the system architecture. Here I refer to SSE4 build. 

System details:

$ cat /proc/cpuinfo | grep "model name" | uniq
model name	: Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz

$ clang++-3.8 --version
clang version 3.8.0-2ubuntu3~trusty4 (tags/RELEASE_380/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Grid:

$ git log | head -n 1
commit 4a8c4ccfba1d05159348d21a9698028ea847e77b

$ ./configure CXX=clang++-3.8 CXXFLAGS="-std=c++11 -O3" --enable-simd=SSE4 --enable-precision=double --disable-openmp

$ cat grid.configure.summary 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Summary of configuration for Grid v0.7.0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
----- GIT VERSION -------------------------------------
commit: 4a8c4cc
branch: develop
date  : 2017-06-02
----- PLATFORM ----------------------------------------
architecture (build)        : x86_64
os (build)                  : linux-gnu
architecture (target)       : x86_64
os (target)                 : linux-gnu
compiler vendor             : clang
compiler version            : 4.2.1
----- BUILD OPTIONS -----------------------------------
SIMD                        : SSE4
Threading                   : no
Communications type         : none
Default precision           : double
Software FP16 conversion    : yes
RNG choice                  : sitmo
GMP                         : yes
LAPACK                      : no
FFTW                        : no
LIME (ILDG support)         : no
HDF5                        : no
build DOXYGEN documentation : no
----- BUILD FLAGS -------------------------------------
CXXFLAGS:
    -I/home/noname/git-clone-080617/Grid/include
    -msse4.2
    -O3
    -std=c++11
    -O3
LDFLAGS:
    -L/home/noname/git-clone-080617/build-sse-clang-3.8/lib
LIBS:
    -lmpfr
    -lgmp
-------------------------------------------------------

Failing binaries:

./tests/hmc/Test_hmc_EODWFRatioLsVectorised

...
Grid     : Message    : 188 ms : -- Thermalization
Test_hmc_EODWFRatioLsVectorised: ../../Grid/lib/qcd/action/fermion/CayleyFermion5Dvec.cc:789: void Grid::QCD::CayleyFermion5D<Grid::QCD::DomainWallVec5dImpl<Grid::Grid_simd<std::complex<double>, __attribute__((__vector_size__(2 * sizeof(double)))) double>, 3, Grid::QCD::CoeffReal> >::MooeeInternal(const FermionField &, FermionField &, int, int) [Impl = Grid::QCD::DomainWallVec5dImpl<Grid::Grid_simd<std::complex<double>, __attribute__((__vector_size__(2 * sizeof(double)))) double>, 3, Grid::QCD::CoeffReal>]: Assertion `_Matp->size()==Ls*LLs' failed.
Aborted (core dumped)

./tests/core/Test_fft_gfix

...
Grid     : Message    : 3 ms : Grid is setup to use 1 threads
*****************************************************************
* Testing we can gauge fix steep descent a RGT of Unit gauge    *
*****************************************************************
 Initial plaquette 1
Test_fft_gfix: /home/men04359/QPACE4/git-clone-080617/Grid/include/Grid/algorithms/FFT.h:173: void Grid::FFT::FFT_dim(Lattice<vobj> &, const Lattice<vobj> &, int, int) [vobj = Grid::iScalar<Grid::iScalar<Grid::iMatrix<Grid::Grid_simd<std::complex<double>, __attribute__((__vector_size__(2 * sizeof(double)))) double>, 3> > >]: Assertion `0' failed.
Aborted (core dumped)

./tests/core/Test_cf_coarsen_support
...
Grid     : Message    : 321 ms :  SurfaceLists 0 0
Grid     : Message    : 322 ms : s = 0 Beta 4.77389 Aee 10.5026 See 10.5026
Grid     : Message    : 322 ms : s = 1 Beta 2.72314 Aee -5.99092 See -6.08613
Grid     : Message    : 322 ms : s = 2 Beta 1.87546 Aee 4.12601 See 4.29032
Grid     : Message    : 322 ms : s = 3 Beta 1.35352 Aee -2.97773 See -3.21082
Grid     : Message    : 322 ms : s = 4 Beta 0.969697 Aee 2.13333 See 2.44478
Grid     : Message    : 322 ms : s = 5 Beta 0.65625 Aee -1.44375 See -1.85278
Grid     : Message    : 322 ms : s = 6 Beta 0.380952 Aee 0.838095 See 1.37782
Grid     : Message    : 322 ms : s = 7 Beta 0.125 Aee -0.275 See -1.00078
Grid     : Message    : 322 ms : s = 8 Beta 0 Aee 1.22222 See 2.22144
Test_cf_coarsen_support: ../../Grid/lib/qcd/action/fermion/WilsonFermion5D.cc:235: virtual void Grid::QCD::WilsonFermion5D<Grid::QCD::WilsonImpl<Grid::Grid_simd<std::complex<double>, __attribute__((__vector_size__(2 * sizeof(double)))) double>, Grid::QCD::FundamentalRep<3>, Grid::QCD::CoeffReal> >::DhopDir(const FermionField &, FermionField &, int, int) [Impl = Grid::QCD::WilsonImpl<Grid::Grid_simd<std::complex<double>, __attribute__((__vector_size__(2 * sizeof(double)))) double>, Grid::QCD::FundamentalRep<3>, Grid::QCD::CoeffReal>]: Assertion `dirdisp>=0' failed.
Aborted (core dumped)

./tests/core/Test_fft

...
Grid     : Message    : 0 ms : Grid is setup to use 1 threads
*************************************************
Testing Fourier from of known plane wave         
*************************************************
 Benchmarking FFT of LatticeComplex  
Test_fft: /home/men04359/QPACE4/git-clone-080617/Grid/include/Grid/algorithms/FFT.h:173: void Grid::FFT::FFT_dim(Lattice<vobj> &, const Lattice<vobj> &, int, int) [vobj = Grid::iScalar<Grid::iScalar<Grid::iScalar<Grid::Grid_simd<std::complex<double>, __attribute__((__vector_size__(2 * sizeof(double)))) double> > > >]: Assertion `0' failed.
Aborted (core dumped)

./tests/core/Test_fftf

...
Grid     : Message    : 0 ms : Grid is setup to use 1 threads
Test_fftf: /home/men04359/QPACE4/git-clone-080617/Grid/include/Grid/algorithms/FFT.h:173: void Grid::FFT::FFT_dim(Lattice<vobj> &, const Lattice<vobj> &, int, int) [vobj = Grid::iScalar<Grid::iScalar<Grid::iScalar<Grid::Grid_simd<std::complex<float>, __attribute__((__vector_size__(4 * sizeof(float)))) float> > > >]: Assertion `0' failed.
Aborted (core dumped)

./tests/core/Test_poisson_fft

...
Grid     : Message    : 0 ms : Grid is setup to use 1 threads
Test_poisson_fft: /home/men04359/QPACE4/git-clone-080617/Grid/include/Grid/algorithms/FFT.h:173: void Grid::FFT::FFT_dim(Lattice<vobj> &, const Lattice<vobj> &, int, int) [vobj = Grid::iScalar<Grid::iScalar<Grid::iScalar<Grid::Grid_simd<std::complex<double>, __attribute__((__vector_size__(2 * sizeof(double)))) double> > > >]: Assertion `0' failed.
Aborted (core dumped)

./benchmarks/Benchmark_mooee
...
Grid     : Message    : 130255 ms : ******************
Grid     : Message    : 131631 ms : #### M5D calls report 
Grid     : Message    : 131631 ms : CayleyFermion5D Number of M5D Calls     : 1001
Grid     : Message    : 131631 ms : CayleyFermion5D ComputeTime/Calls       : 1372.01 us
Grid     : Message    : 131631 ms : Average mflops/s per call                : 1719.58
Grid     : Message    : 131631 ms : Average mflops/s per call per rank       : 1719.58
Grid     : Message    : 131631 ms : Called Mooee 1374.28 us
Grid     : Message    : 131631 ms : ******************
Benchmark_mooee: ../../Grid/lib/qcd/action/fermion/CayleyFermion5Dvec.cc:789: void Grid::QCD::CayleyFermion5D<Impl>::MooeeInternal(const FermionField&, Grid::QCD::CayleyFermion5D<Impl>::FermionField&, int, int) [with Impl = Grid::QCD::DomainWallVec5dImpl<Grid::Grid_simd<std::complex<double>, __vector(2) double>, 3, Grid::QCD::CoeffReal>; Grid::QCD::CayleyFermion5D<Impl>::FermionField = Grid::Lattice<Grid::iScalar<Grid::iVector<Grid::iVector<Grid::Grid_simd<std::complex<double>, __vector(2) double>, 3>, 4> > >]: Assertion `_Matp->size()==Ls*LLs' failed.
Aborted (core dumped)

Furthermore, using 

$ g++-6 --version
g++-6 (Ubuntu/Linaro 6.3.0-18ubuntu2~14.04) 6.3.0 20170519
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

instead of clang++-3.8 and

$ ./configure CXX=g++-6 CXXFLAGS="-std=c++11 -O3" --enable-simd=SSE4 --enable-precision=double --disable-openmp

I get

./benchmarks/Benchmark_mooee

...
Grid     : Message    : 128320 ms : ******************
Grid     : Message    : 129698 ms : #### M5D calls report 
Grid     : Message    : 129698 ms : CayleyFermion5D Number of M5D Calls     : 1001
Grid     : Message    : 129698 ms : CayleyFermion5D ComputeTime/Calls       : 1373.87 us
Grid     : Message    : 129698 ms : Average mflops/s per call                : 1717.26
Grid     : Message    : 129698 ms : Average mflops/s per call per rank       : 1717.26
Grid     : Message    : 129698 ms : Called Mooee 1376.12 us
Grid     : Message    : 129698 ms : ******************
Benchmark_mooee: ../../Grid/lib/qcd/action/fermion/CayleyFermion5Dvec.cc:789: void Grid::QCD::CayleyFermion5D<Impl>::MooeeInternal(const FermionField&, Grid::QCD::CayleyFermion5D<Impl>::FermionField&, int, int) [with Impl = Grid::QCD::DomainWallVec5dImpl<Grid::Grid_simd<std::complex<double>, __vector(2) double>, 3, Grid::QCD::CoeffReal>; Grid::QCD::CayleyFermion5D<Impl>::FermionField = Grid::Lattice<Grid::iScalar<Grid::iVector<Grid::iVector<Grid::Grid_simd<std::complex<double>, __vector(2) double>, 3>, 4> > >]: Assertion `_Matp->size()==Ls*LLs' failed.
Aborted (core dumped)

Best,

Nils

**Comment by paboyle** [comment]
Think this is all working now. Closing
