### ISSUE TITLE
Bug in tensor poke

### ISSUE THREAD

**Issue by lehner** [paboyle/Grid#126]
void diquark(T& D, const T& Q1, const T& Q2) {
  typedef typename T::scalar_type Coeff_t;
  struct datum { int a,b,c; Coeff_t sign; };
  const std::vector<datum> eps = {
    { 0,1,2,+1.0 },
    { 1,2,0,+1.0 },
    { 2,0,1,+1.0 },
    { 0,2,1,-1.0 },
    { 1,0,2,-1.0 },
    { 2,1,0,-1.0 }
  };
  D = zero;
  for (int i1=0;i1<(int)eps.size();i1++) {
    for (int i2=0;i2<(int)eps.size();i2++) {
      auto v = peekColour(D,eps[i1].a,eps[i2].a);
      v += transpose(peekColour(Q1,eps[i1].b,eps[i2].b)) *
        peekColour(Q2,eps[i1].c,eps[i2].c) * eps[i1].sign * eps[i2].sign;
      pokeColour(D,v,eps[i1].a,eps[i2].a);
    }
  }
}

fails to compile.

Can be fixed by correcting decltype in Tensor_index.h :

    void pokeIndex(iVector<vtype,N> &ret, const iVector<decltype(TensorIndexRecursion<Level-1>::peekIndex(ret._internal[0],0,0)),N> &arg, int i,int j)
  
and

    void pokeIndex(iMatrix<vtype,N> &ret, const iMatrix<decltype(TensorIndexRecursion<Level-1>::peekIndex(ret._internal[0][0],0,0)),N> &arg, int i,int j)

**Comment by paboyle** [comment]
Patched in develop.
