### ISSUE TITLE
Start of accelerator port

### ISSUE THREAD

**Issue by paboyle** [paboyle/Grid#141]
Started a branch, feature/gpu-port.

i) Since I'm doing a global edit anyway, I'm sprucing up a few things.

a) namespace -> Macros. 
 NAMESPACE_BEGIN(Grid);
 NAMESPACE_END(Grid);
 Rationale: 
   - Prevents editor indentation, something I've been fighting auto format for some time.
      Makes more edit environments happy with my not indenting pointlessly a global namespace 
      parenthesis.

b) Remove QCD namespace. 
   Annoying as not all theories are QCD and splits things annoyingly. In hindsight the namespace was a    mistake.

c) Indentation
   - I've since figured there is at least an emacs control to NOT indent namespaces.
   - Since I have two ways to make editors happy with the Indentation I've wanted all along,
      I'm happy to force format to Emacs C++ mode.
  - scripts/format does this.
  - There was a whole bunch of my code with indentation corrupted by Guido, which annoyed the heck  out of me. I have globally fixed this in this branch. It will of course cause conflicts on other branches,
 but people will just have to resolve these carefully. Avoiding biting the bullet out of fear of conflicts simply  bans global code hygiene steps.

ii) Plan to support "marking up" functions for nvcc acceleration without introduction of explicit 
use of CUDA constructs. 

Plan lambda capture:

threaded_loop( (start; check ; incr) , { 
   Body;
});

accelerated_loop( (start; check ; incr) , { 
   Body;
});

accelerated_unroll( (start; check; iter), { 
    Try to force unroll
});

+ nested versions.

iii) Memory management
Use all lattice fields as cudaMallocManaged memory, custom C++ allocator.
(how to get huge pages NVIDIA ?)

Comments welcome

iv) ET system -> copy the ET hacks from the work I did with Meifeng and (later) Alejandro & Aleksander.

v) Make Nd a template param to Lattice.
Replace std::vector<int>  with std::array<int, Nd>, to avoid mallocs on GPU
type code.

vi) Get to point of latticeworking, no dirac ops. no Cshift. Site local off load.
Get Benchmark_su3 working

vii) Add cshift & apply tests

viii) Stencil can run the comms ok from host with managed memory, at least for a first pass.

ix) Get the Generic and Hand kernels running in offload mode.
Possibly can do a CUDA kernel, drop in like the ASM for x86.

**Comment by paboyle** [comment]
p.s. I've done i) a), b), c) over the weekend.

**Comment by coppolachan** [comment]
I'm collecting here some compilation tips at this stage of the development
Some of these are specific to my environment but I think it is still useful to report as a reference.
N.B. Still I cold not get a successful compilation.

Using NVCC 9.1, kernel 4.13. Default gcc: 7.2.0

- eigen needs the latest version to compile with CUDA 9.1
use 
`wget http://bitbucket.org/eigen/eigen/get/tip.tar.bz2 --no-check-certificate`

in the root of the code tree and then 
.`/scripts/update_eigen.sh `basename http://bitbucket.org/eigen/eigen/get/tip.tar.bz2` && rm `basename http://bitbucket.org/eigen/eigen/get/tip.tar.bz2``

Compiling with gcc 5.5 and 6.3 does not work because of an inconsistency in the avx512vlintrin.h file see https://github.com/tensorflow/tensorflow/issues/16887
Tentative compilation flag:
`CXX=nvcc CXXFLAGS="-ccbin g++-5 --expt-extended-lambda --expt-relaxed-constexpr -std=c++11 " ../../Grid/configure --enable-precision=single --enable-simd=GEN  --enable-comms=none 
`
Did not try with other gcc versions yet, gcc 5.4 should work. 

NVCC 9.1 + clang 4.0.1
using GNU libstdc++ we have to modify the accessor macro in Pragmas.h to this because the header for LLVM is different

```
#define NVCC_DECLARE_STD_VECTOR_ACCESSOR(Type) \
template <> accelerator_inline typename std::vector<Type>::reference       std::vector<Type>::operator[](std::vector<Type>::size_type __n) noexcept       { return this-> _Vector_base<Type, std::vector<Type>::allocator_type >::_M_impl._M_start[__n]; } \
template <> accelerator_inline typename std::vector<Type>::const_reference std::vector<Type>::operator[](std::vector<Type>::size_type __n) const noexcept { return this-> _Vector_base<Type, std::vector<Type>::allocator_type >::_M_impl._M_start[__n]; }

```
Notice also the noexcept, required.

For the moment this is as far as I could get because clang is mixing libraries and I am getting an error on the compilation of the tuple class

**Comment by coppolachan** [comment]
Some progress:
Compiles with the following compilation flags for CUDA 9.1, clang 4.0.1 and GNU STL version 5 (with lot of warnings of calling host function from host device functions)
```
CXX=nvcc CXXFLAGS="-ccbin clang++ --expt-extended-lambda --expt-relaxed-constexpr -I/usr/include/c++/5/ -I/usr/lib/gcc/x86_64-linux-gnu/5/ -I/usr/include/x86_64-linux-gnu/c++/5/ -I/usr/include/c++/5/backward/ -std=c++11 -D__CORRECT_ISO_CPP11_MATH_H_PROTO -Xcompiler -std=c++11,-nostdinc++" ../../Grid/configure --enable-precision=single --enable-simd=GEN  --enable-comms=none
```

but fails the linking in the compilation of the executables

**Comment by paboyle** [comment]
gmp.h HACK
Peters-Laptop:build-nvcc peterboyle$ diff /usr/local/Cellar/gmp/6.1.2_1/include/gmp.h  /usr/local/Cellar/gmp/6.1.2_1/include/gmp.h~
416c416
< #if defined (__cplusplus) 
---
> #if defined (__cplusplus) && ! defined (__GMP_EXTERN_INLINE)


My compiled flags (ugh)

**which nvcc**
/Developer/NVIDIA/CUDA-9.1/bin//nvcc

**Peters-Laptop:build-nvcc peterboyle$ clang++ --version**
clang version 3.8.1 (tags/RELEASE_381/final)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-3.8/bin

**Configure:**

../configure --enable-simd=GEN --enable-precision=double --with-lime=/Users/peterboyle/SciDac/install/ --enable-comms=none CXX=nvcc CXXFLAGS="-std=c++11 -Xcompiler -fopenmp -Wno-deprecated-gpu-targets --expt-relaxed-constexpr --expt-extended-lambda --relocatable-device-code=true --gpu-architecture=sm_60" CFLAGS=-Wno-deprecated-gpu-targets

**Comment by paboyle** [comment]
Status update:

Looks like almost clean on all compilers on the CI server. Just wrestling a little with AVX512 but will go shortly if not already fixed. Waiting on the CI to process my last patch.

*** on my laptop *** (not committed)

I switched over to cudaMallocManaged allocator, and put the accelerator_loop into 
an offload CUDA kernel call.

This *compiled* 

Run time errors arise, naturally,  (cudaMallocManaged failed) probably because
I don't have an Nvidia GPU on my laptop.

Getting to the point where I have to pull across to Summit for further development of the software.

Fairly sizeable milestone, even if I do know the performance will initially suck until I get read
coalescing done...

Some record of my notes:

--------------------------------------------------------------------------------------------
Todo:
--------------------------------------------------------------------------------------------

--- Make StencilAccelerator usable on GPU; avoid copy by value; integrate the LebesgueOrder vector/pointer

--- Coalesce strategy not right yet (not even attempted, to be fair).

--- Fix Explicit OMP constructs for comms overlap in DhopInternal and below.
    accelerator_loop_in_thread_region();???

-- Make thread_loop same interface as accelerator_loop. 
   -- need an accelerator_loop that is not based on begin(), end() view. 
   -- delete parallel_for

-- Protection
    -- Private hide grid._ndimension, other internals (?)
    -- Prevent direct use of ._grid         (done?)

-- FIXME clean; 53 items to audit

-- Audit integer loop counters & types. Move to 64 bit throughoutt ; Use Integer; 32bit required for mask vectors as Nsimd must match float vector?

-- Lattice_reduction.h problematic. *** doing on CPU for now(accelerated) Bit repro GPU reduction?


--------------------------------------------------------------------------------------------
Untested
--------------------------------------------------------------------------------------------

---DONE allocator for CUDA offload
---DONE Allocator -> CudaMallocManaged option
---DONE Make kernel call; block and such tuning to do

--------------------------------------------------------------------------------------------
Done:
--------------------------------------------------------------------------------------------

--- ET sector:

  -- DONE where, merge, extract are the only choking things
  -- DONE -- ET changes to offload cleanly, consistent with work I did at BNL
  -- DONE Need to work on code to build the right expression capturing LatticeAccelerator, or data by value.
  -- DONE LATTICE VIEW OBJECT : Problem: rule of 5 & copy by value 
    -- closure may be difficult
      -- Want the copy constructor to
     a) make a deep copy in the case of host code
     b) make a shallow copy in the case of device lambda calls.
     This probably forces change to accelerator_loop syntax. Turn a Lattice into a LatticeAccelerator.
     Annoying global edit that makes the interface ugly.

     Make a LatticeView object, and only that object is addressable (operator []). Forces the change of
     copy constructor. This is probably why Kokkos uses views. A view as a reference which is trivially copyable.
     Might need/enable to use something like coalesced pointer after all.


  -- DONE: ALMOST DONE Stencil & kernel calls
  -- DONE: Move thread_loops in fermion to accelerator (overlapped comms case only, sequential done)
  -- DONE: Clean parallel region idioms using a per thread std::vector dynamic array & audit
  -- DONE: Lattice peek poke need to be std::array for coor; two stage; phase the 
  -- DONE: move on external interface and move on Cartesian interface
  -- DONE Tensor extract merge is host only. Must use fixed range arrays instead of std::vector
  -- DONE Tensor predicatedWhere etc... fixed range arrays and accelerator mark up.
  -- DONE  std::array (or similar) in place of std::vector for coordinates; AcceleratorVector done
  -- DONE Lattice_where is obselete.. Killed it.
  -- DONE Split Lattice into LatticeAccelerator and Lattice with the accelerator a subset which should
          into a flat data structure without references.
  -- DONE VA_ARGS in Lattice_where / COMMA_SAFE is ugly
  -- DONE Grid::Zero is being problematic; replace with Zero()
      -- another global edit. Around 2h to 1/2 day. work

  -- DONE Operator [] use exclusively hide _odata. 
                           and ._odata
                               .checkerboard

  -- DONE Lattice - Vector container issues as std::vector is __host__ ; change over and make work again
     -- Replaced vector with my own naked pointer.
-- DONE Removed STL container from Lattice class
-- DONE Tensor extract merge is host only. Must use fixed range arrays instead of std::vector
HACKS:
-----------------------------------------------------------
-- Fixed the ::sin ::pow, ::sqrt issues in CPU version (painful) CUDA was introducing these
   Used using std::pow, using std::sqrt.
-- real ; needed to remove Grid::real and replace in several algorithm files. I made a mess
-- GMP was compiling to place inline functions as not inline. Had to fix gmp.h which is not ideal.
   Probably have to place #include <gmp.h> in a guard that undefs __GNU_C__ 

-- Eigen
   Place in a guard that undefs __NVCC__ etc...

-- Undocumented pragmas on disable warnings pulled from strings run on library binary


-- nvcc 
----------------------------------------
Configure:

        Had to doctor AC_OPENMP choice to force ac_openmp on

        ../configure --enable-simd=GEN \
        --enable-precision=double \
        --with-lime=/Users/peterboyle/SciDac/install/ \
        --enable-comms=none \
        CXX=nvcc \
        CXXFLAGS="-std=c++11 -Xcompiler -fopenmp"

        Set a "$HOME/bin/clang++ " that points to clang-3.8 from macports
        nvcc from CUDA 9.1  (despite not support compile on MacOS X 10.13)


Original plan:
-----------------
0)  Audit: --- DONE
Simd, Tensors, Lattice : __host__ __device__ on everything is required. 
                         All these functions are inline.
Conclusion:  accelerate_inline macro; relevant for CSA too potentially
                                        remove strong_inline

--
Lattice ET eval etc... make compliant in ET.cc way. Make SU3 x SU3 work; don't link -lGrid (header only?)
operator ~ instead of = available only to the Benchmark_su3 code at first

-- WilsonKernels           ; Could just write a .cu file
-- Cshift and Cartesian... ; run on host for now.
-- Stencil                 ; run on host for now.

1) make whole thing compile through nvcc --- DONE
2) NAMESPACE MACROS GLOBAL EDIT          --- DONE
3) PARALLEL FOR DEPRECATE                --- DONE

threaded_loop
threaded_nest_loop(2) 
accelerator_inline // Inline a function
accelerator_unroll // Unrolled loop
accelerator_loop   // Pipeline

Accelerate loops test via lambda

; Code structure sort of ok. parallel_for finish and remove.

4) Two types of offload required:  ---- DONE

 Expression template engine -> ET.cc style
 accelerator_loop           -> site local lambda capture

5) allocator for CUDA offload (not done)
6) Get to point of latticeworking, no dirac ops. no Cshift. Site local off load;---  DONE

Code volume:

 157 total  in lib/threads/
 438 total  in lib/allocator/
 816 total  in lib/cartesian/
3717 total  in lib/tensors/
4449 total  in lib/lattice/
1752 total  in lib/communicator/
8918 total  in lib/simd/

Perhaps  8k lines of code in lattice and tensors.
Do this for Nsimd = 1 to begin with.

7) Add cshift & tests -- DONE
 720 total  in lib/cshift/

8) Add stencil -- DONE
1588 total  in lib/stencil/

**Comment by paboyle** [comment]
Closed this branch.

There is of course still work to do, but this is now believed to have at least core functionality running through to HMC and is not known to break develop.

754 individual commits, many of which were many files at once global edits.

Satisfying.
