### ISSUE TITLE
More Issues with gcc 6.3.1 and AVX512

### ISSUE THREAD

**Issue by kkissell** [paboyle/Grid#143]
Building on Skylake GCE virtual machine.

[kkissell@centhpc-64core-1 build]$ cat /proc/cpuinfo | grep 'model name' | uniq
model name      : Intel(R) Xeon(R) CPU
[kkissell@centhpc-64core-1 build]$ gcc --version
gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)

Configure command was:

../configure --enable-precision=double --enable-simd=AVX512 --enable-comms=mpi-auto --prefix=$HOME/DiRAC/Bench

lib/qcd/action/fermion/CayleyFermion5Dvec.cc

Fails to build, reporting errors on lines 472 and 704:

../lib/qcd/action/fermion/CayleyFermion5Dvec.cc:472:17: error: dependent-name ‘Grid::QCD::CayleyFermion5D<Impl>::Simd:: scalar_type’ is parsed as a non-type, but instantiation yields a type
  a2 = a2+sizeof(Simd::scalar_type);

and

../lib/qcd/action/fermion/CayleyFermion5Dvec.cc:704:17: error: dependent-name ‘Grid::QCD::CayleyFermion5D<Impl>::Simd:: scal
ar_type’ is parsed as a non-type, but instantiation yields a type
  a2 = a2+sizeof(Simd::scalar_type);

Changing those two lines to be:

  a2 = a2+sizeof(typename Simd:scalar_type);

Resolves that problem, but the same line of code is copied/generated in a few other places:

../lib/qcd/action/fermion/DomainWallEOFAFermionvec.cc:478:42: error: dependent-name ‘Grid::QCD::DomainWallEOFAFermion<Impl>::Simd:: scalar_type’ is parsed as a non-type, but instantiation yields a type

../lib/qcd/action/fermion/MobiusEOFAFermionvec.cc:856:32: error: dependent-name ‘Grid::QCD::MobiusEOFAFermion<Impl>::Simd:: 
scalar_type’ is parsed as a non-type, but instantiation yields a type

And a similar insertion of an explicit "typename" in each case allows the build to get past it (to the next problem, which seems unrelated).

**Comment by coppolachan** [comment]
Thanks Kevin,

I can reproduce similar errors with gcc 6.3.0
plus errors like this
`/tmp/ccRvp5cT.s:3339: Error: no such instruction: `vpxord %zmm20,%zmm20,%zmm20'`

I am investigating the issue.

**Comment by coppolachan** [comment]
Patch committed to develop
