### ISSUE TITLE
AVX512 flags/bindings for gcc 6.3.1

### ISSUE THREAD

**Issue by kkissell** [paboyle/Grid#144]
As per my previous issue report, I'm trying to build Grid for Skylake in Google Cloud.

[kkissell@centhpc-64core-1 build]$ cat /proc/cpuinfo | grep 'model name' | uniq
model name      : Intel(R) Xeon(R) CPU
[kkissell@centhpc-64core-1 build]$ gcc --version
gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)

With the configure line:
../configure --enable-precision=double --enable-simd=AVX2 --enable-comms=mpi-auto --prefix=$HOME/DiRAC/Bench

There are issues with the gcc intrinsic binding:

In file included from /opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/immintrin.h:57:0,
                 from /opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/x86intrin.h:48,
                 from /home/kkissell/DiRAC/Grid/include/Grid/perfmon/PerfCount.h:47,
                 from /home/kkissell/DiRAC/Grid/include/Grid/GridCore.h:44,
                 from /home/kkissell/DiRAC/Grid/include/Grid/qcd/action/fermion/FermionCore.h:31,
                 from ../../lib/qcd/action/fermion/WilsonFermion.cc:33:
/opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/avx512dqintrin.h: In member function ‘Out_type Grid::Op
timization::Reduce<Out_type, In_type>::operator()(In_type) [with Out_type = unsigned int; In_type = __vector(8) long long int]’
:
/opt/rh/devtoolset-6/root/usr/lib/gcc/x86_64-redhat-linux/6.3.1/include/avx512dqintrin.h:1596:1: error: inlining failed in call
 to always_inline ‘__m256i _mm512_extracti32x8_epi32(__m512i, int)’: target specific option mismatch
 _mm512_extracti32x8_epi32 (__m512i __A, const int __imm)

Looking at the generated makefile, I see that specifying AVX512 as the SIMD model leads to a set of gcc flags, -mavx512f -mavx512cd -mavx512er -mavx512pf that are those specified as implemented by Knights Landing.  ER and PF are *not* available on Skylake, but Skylake does have the BW, DQ, and VL extensions that may or may not be useful in Grid.  Other source bases have created an "AVX512-SKYLAKE" specifier to distinguish builds for Skylake from those for KNL.  That might be worth considering here.  But note that manually hacking the Makefile to remove the unsupported KNL extensions and add the Skylake flags did not fix this particular problem.

**Comment by coppolachan** [comment]
Modified the behaviour:
use 
`
--enable-simd=SKL
`

Suggested flags on CXXFLAGS
`-Wno-ignored-attributes -Wno-cpp`

Tested on gcc 7 and 6.4.0

**Comment by aportelli** [comment]
Is SKL really the best label? I think AVX512 is better, keeping KNL as the special case as the MIC architecture. Presumably we will quickly have “generic” Xeon chips which are not Skylake with AVX512. This is similar to us having AVX and AVX2 but not mentioning Sandy Bridge or Haswell or others.

**Comment by coppolachan** [comment]
Probably a better flags would be SKL-AVX512 since I am forcing -march=skylake-avx512

**Comment by kkissell** [comment]
Intel complicated our lives here.  Just tagging "Skylake" isn't good, because the desktop Skylakes don't have the AVX512 implementation. ;o(   And we've been collectively burned by KNL, because it was the first AVX512 product, and therefore the target of many people's "AVX512" builds, but in fact had a rather idiosyncratic AVX512 implementation.  It may or may not be worth anyone's time to replace "legacy" AVX512 with "KNL-AVX512", but I second coppolachan's suggestion of SKL-AVX512 (or AVX512-SKL) for server-class Skylakes.

**Comment by aportelli** [comment]
Ok thanks, I would vote for AVX512-KNL and AVX512-SKL.
