### ISSUE TITLE
MDWF Support

### ISSUE THREAD

**Issue by bcolquhoun** [paboyle/Grid#147]
Missing from the Hadrons package is full support for Mobius DWF. Is it possible for this to be supported?

A specific issue identified is the absence of a Dminus term in MDWF source compared to DWF. Communication with Guido indicates that missing support for the action in e.g. extras/Hadrons/Modules/MFermion/GaugeProp.hpp will prevent me from adding this just now.

Thanks.

**Comment by coppolachan** [comment]
One suggestion is making also the Action an input of the module so we can access the Dminus. Do not like very much because it is redundant info since we have the solver that knows the action.
Could we eventually access the Action from the Solver module?

Another option could be having another module for the preparation of the source.

Antonin, any other suggestions that fit better in the Hadrons structure?

**Comment by aportelli** [comment]
It's in the pipeline, the idea is that the action classes (in Grid) will have a virtual method to prepare a source for a solve and that Hadrons will just call it in the solver module. I probably need to check if Peter or I should do it (we probably said something about that but I can't remember).

If there is some urgency to have it work a small hack of Hadrons should do. There is no need to make the action an input for the propagator module. It is already an input of the solver module. From the propagator module you can get the solver module using 
``` cpp
auto actionMod = vm().getModule<RBPrecCG>(par().solver);
``` 
then you can access its parameters through
``` cpp
actionMod->par();
``` 
If you want the fermion operator you can do
``` cpp
auto &mat  = envGet(RBPrecCG::FMat, actionMod->par().action);
```
where you might want to replace `RBPrecCG::FMat` by the specific Möbius action. If this is does not working directly just do a `dynamic_cast` of `mat` afterward.

All that is of course pretty ugly and breaking Hadrons modularity but that should solve it for now. Once we have implemented the source preparation at the action level everything will be automatised.

I hope this helps.

**Comment by coppolachan** [comment]
Thanks, that would probably solve temporarily Brian's problem while he waits for a long term solution.

**Comment by bcolquhoun** [comment]
Thanks for the assistance.

I had a look at this just now and there are some snags. The first line you gave, Antonin, doesn't work straight out the box. Referring to RBPrecCG gives " error: identifier "RBPrecCG" is undefined " at compile time.

A secondary issue is that the branch I have been using is quite out of sync with the current status. The VirtualMachine class doesn't even exist, for example. I tried the above by taking a branch from the most up-to-date feature/hadrons to get that error. What would you recommend is the best approach form here? Should I take a new branch from feature/hadrons and re-implement the updates made, otherwise merge the updates, or something else?

**Comment by aportelli** [comment]
My example code was mainly a sketch to illustrate that the functionality is here to hack it while we work on the permanent solution. It needs to be checked and adapted. Probably what is missing in what you mentioned is the namespace, i.e. you should use `MSolver::RBPrecCG`. There might be other things of this kind.

The best approach is that you update you code to the new Hadrons interface first, then try to implement something like what I described. Guido and I can help with the conversion but looking at other modules should be self-explanatory.

**Comment by paboyle** [comment]
Close as the physical fermions interface should have sorted this?
