### ISSUE TITLE
Test_ildg_io segfault

### ISSUE THREAD

**Issue by cpviolator** [paboyle/Grid#156]
The function `writeConfiguration` in `lib/parallelIO/IldgIO.h` contains an `fclose(File)` but there is also an `fclose(File)` in `Test_ildg_io.cc` which causes the segfault. I would have pushed a fix but I don't think I have permissions to do so.

**Comment by paboyle** [comment]
Patched develop thanks

**Comment by paboyle** [comment]
Can you confirm I can close?
