### ISSUE TITLE
GRID_OMP preprocessor not defined in AlignedAllocator.h

### ISSUE THREAD

**Issue by rauteric** [paboyle/Grid#161]
Hello,

In [AlignedAllocator.h](https://github.com/paboyle/Grid/blob/f089bf56296fea05b47a4736550ce7cb1c19abf9/lib/allocator/AlignedAllocator.h#L172), there is an OpenMP loop to do NUMA first touch optimization, wrapped in the preprocessor `GRID_OMP`. However, `GRID_OMP` is defined in the header `Threads.h`, which is not included in `AlignedAllocator.h`. Therefore, `GRID_OMP` is not defined in `AlignedAllocator.h`, so the first touch optimization is not used and consequently performance is reduced when threads from one process run on multiple NUMA domains.

This could be solved by including the `Threads.h` header in `AlignedAllocator.h`. Alternatively, `#ifdef GRID_OMP` could be replaced by `#ifdef GRID_NUMA`, which seems to be a flag intended for this purpose but is currently unused.

**Comment by paboyle** [comment]
You are suppose to include Grid.h, or GridCore.h which includes the sub-includes in the right order.

I don't support including single files deep in the tree, just like Linux does not support direct inclusion of internal files.
