### ISSUE TITLE
Test_laplacian_force fails on dirac-ITT-fix

### ISSUE THREAD

**Issue by taki-jaro** [paboyle/Grid#162]
`$ make check` done on version from tag `dirac-ITT-fix` fails on  Test_laplacian_force with message:
```
Grid     : Message    : 691 ms : Requesting 1073741824 byte stencil comms buffers 
Grid     : Message    : 691 ms : Grid is setup to use 48 threads
Approximation bounds are [0.001,1]
Precision of arithmetic is 64
Grid     : Message    : 795 ms : Generating degree 10 for x^(1/2)
Degree of the approximation is (10,10)
Approximating the function x^(1/2)
Iteration 0 spread 1e+37 delta 0.25
Delta too small, try increasing precision
Test_laplacian_force: ../../lib/algorithms/approx/Remez.cc:154: double AlgRemez::generateApprox(int, int, unsigned long, unsigned long, int, double *, int *): Assertion `0' failed.

Delta too small, try increasing precision
```

As far as I understand the approximation of sqrt(x) function fails to converge
Status after each iteration in AlgRemez::genrateApprox: 
[laplacian_force.log](https://github.com/paboyle/Grid/files/1934595/laplacian_force)

Platform:
- procesor: 2x Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
- OS: CentOS 7.4
- compiler: `icpc (ICC) 17.0.6 20171215`
- configure command: `$ ../configure --enable-precision=double --enable-simd=AVX2 --enable-comms=mpit-auto --enable-mkl CXX=icpc MPICXX=mpiicpc --prefix=/opt/grid_intel`
- [config.log](https://github.com/paboyle/Grid/files/1934505/config.log)
- [grid.configure.summary](https://github.com/paboyle/Grid/files/1934510/grid.configure.summary.log)
- `make V=1` log: 
[makeV.log](https://github.com/paboyle/Grid/files/1934596/makeV.log)
- `make -C tests/forces/ tests V=1` log: 
[makeV_forces.log](https://github.com/paboyle/Grid/files/1934597/makeV_forces.log)

**Comment by paboyle** [comment]
The test was not indented to be included in our procurement benchmarking, and likely fails because the  MPFR and GMP ware not configured
