### ISSUE TITLE
Building Grid for CUDA

### ISSUE THREAD

**Issue by loreson** [paboyle/Grid#164]
Hi everyone, 
Im not sure, if this is the right place for this question, but I did not find anything like a mailing list.

I'm trying to build the feature/gpu-port branch  for CUDA, and getting the following error:

ptxas fatal   : Unresolved extern function '_ZN4Grid13WilsonKernelsINS_10WilsonImplINS_9Grid_simdIN6thrust7complexIfEENS_12Optimization3vecIfEEEENS_14FundamentalRepILi3EEENS_9CoeffRealEEEE18GenericDhopSiteDagERNS_20CartesianStencilViewINS_7iScalarINS_7iVectorINSH_IS9_Li3EEELi4EEEEENSG_INSH_ISI_Li2EEEEEEERNS_11LatticeViewINSH_INSG_INS_7iMatrixIS9_Li3EEEEELi8EEEEEPSM_iiRKNSP_ISK_EERSX_'

Any suggestions where the problem may be?

**Comment by paboyle** [comment]
It is experimental, pretty much guaranteed to not work, and suggest strongly you wait until I have finished the port.

**Comment by paboyle** [comment]
CUDA instructions are now on line.
