### ISSUE TITLE
../configure does not build make files

### ISSUE THREAD

**Issue by JPRichings** [paboyle/Grid#175]
Hi,

Has the build system been edited since the restructure as i have to run the ./config.status script in build to generate the make files. Is this now the intended behavior?

Regards

James

**Comment by aportelli** [comment]
We cannot do much for you with so few details, I would need a complete description on how to reproduce the problem. Yes the build system has changed several times recently. However CI systems on various platforms and myself build Grid from scratch using the standard procedure and everything is fine.

**Comment by aportelli** [comment]
Hi,

No this is unnecessary. This is still very vague, the sequence you describe is very generic (bootstrap configure make) and does not encounter any problem at least on Tesseract, the Cambridge system, my machine and all our CI builds. If the configure script did not generate makefiles it probably encountered an error, but I can’t say without any form of log or similar information.
