### ISSUE TITLE
Invalid write in stencil (SSE, AVX)

### ISSUE THREAD

**Issue by giltirn** [paboyle/Grid#198]
I tracked down what looks like an error which manifests on our SSE4.2 cluster at CU and will likely also happen for AVX(128-bit) systems in double precision. 

The issue is in Stencil.h (https://github.com/paboyle/Grid/blob/develop/Grid/stencil/Stencil.h) lines 657 and 658 where vectors of length Nsimd are created and are then allocated in a loop with fixed size (2) starting line 662. If Nsimd=1 as it is for a 128-bit double precision complex, then this causes an invalid write that valgrind picked up on. This probably results in memory corruption. 

I worked around it by allocating to a minimum size of 2  (sz = Nsimd > 2 ? Nsimd : 2), but it's not yet clear if that fixes everything (I'm trying to pin down a CG non-converge on a multinode job). Thoughts?

**Comment by paboyle** [comment]
Does not happen for AVX due to it being 256 bit, but it is a bug thanks.
Will patch.

**Comment by paboyle** [comment]
P.S. effect is a stray write over the array bound. If Nsimd is 1 the result is never used, just the first element that was correctly written. Potential for heap corruption depending on the allocator.

I checked glibc: 

https://github.com/bminor/glibc/blob/master/malloc/malloc.c

 Minimum allocated size: 4-byte ptrs:  16 bytes    (including 4 overhead)
			  8-byte ptrs:  24/32 bytes (including, 4/8 overhead)

Which suggests a 32 byte actually minimum allocate, so we get 4 pointers worth "in practice" which is probably why it has not been picked up to date. 

For other allocators there is no guarantee, and audit would be required.

An effort ensuring valgrind clean again is sensible. I've done this in the past a long time ago but it is not automated so catching errant code being committed remains possible.

**Comment by paboyle** [comment]
Think I have fixed this fully in GPU port, and merged develop into GPU port. Will expect to close gpu-port back to develop soon so closing.
