### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by aportelli** [paboyle/Grid#20]
Hi,

As the code is available publicly and certainly receive attention, I think we should license it properly. There is already a GPLv3 text distributed in `COPYING`. It would be safer to mark all source file as prescribed by the FSF guys. I suggest that we add a license header to each individual source file . I propose the following header:
```
/*
 * <filename>.cc, part of Grid
 *
 * Copyright (C) 2015 <author list>
 *
 * Grid is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Grid is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Grid.  If not, see <http://www.gnu.org/licenses/>.
 */
```
Please tell me if you think another license is more suitable.

**Comment by paboyle** [comment]
I think I intended GPL v2. let me look into it.
Peter

> On 27 Oct 2015, at 12:31, Antonin Portelli <notifications@github.com> wrote:
> 
> Hi,
> 
> As the code is available publicly and certainly receive attention, I think we should license it properly. There is already a GPLv3 text distributed in COPYING. It would be safer to mark all source file as prescribed by the FSF guys. I suggest that we add a license header to each individual source file . I propose the following header:
> 
> /*
>  * <filename>.cc, part of Grid
>  *
>  * Copyright (C) 2015 <author list>
>  *
>  * Grid is free software: you can redistribute it and/or modify
>  * it under the terms of the GNU General Public License as published by
>  * the Free Software Foundation, either version 3 of the License, or
>  * (at your option) any later version.
>  *
>  * Grid is distributed in the hope that it will be useful,
>  * but WITHOUT ANY WARRANTY; without even the implied warranty of
>  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>  * GNU General Public License for more details.
>  *
>  * You should have received a copy of the GNU General Public License
>  * along with Grid.  If not, see <http://www.gnu.org/licenses/>.
>  */
> Please tell me if you think another license is more suitable.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/paboyle/Grid/issues/20>.
> 


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by aportelli** [comment]
Hi Peter, I am just bumping this thread because I realised that I already included here an example of license header.

**Comment by paboyle** [comment]
Banner added; I went with GPL v2 due to the over aggressive nature of v3 (forced apple to drop binutils, for example, Torvalds refused to move Linux forward to v3).

scripts/copyright is an easy way to generate copyright banner and author list from git log.

Grid_init prints a message like (which works out ok in a fixed font, and comes out in colour
in a colour term):

 GGG       RRRR     IIIII   DDD
G      G     R       R     I     D    D
G              R       R     I     D      D
G   GGG   RRRR      I     D      D
G      G     R      R      I     D     D
 GGGG     R       R   IIIII   DDD


    Copyright (C) 2015 Peter Boyle, Azusa Yamaguchi, Guido Cossu, Antonin Portelli and other authors

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    Grid     : Message      : 0 ms : Grid is setup to use 1 threads
    ....
