### ISSUE TITLE
Criteria for closing GPU port back to develop.

### ISSUE THREAD

**Issue by paboyle** [paboyle/Grid#223]
I have got feature-gpu port producing good multi-node performance on Tesseract.
2.8 TF/s per blade (4x V100's) with two blades in calculation. Obviously 5.6TF/s total is hardly faster than I get with a single blade, but... bigger local volume than 24^4 might help as will half precision comms.

It is ready to push back to develop, perhaps after I add Gianluca's deterministic reduction.

We should think about sign off procedure as this is a very big commit.

**Comment by aportelli** [comment]
Running a simple Hadrons workflow (e.g. old-school meson 2-point functions) on the RBC-UKQCD 24^3 where we already have the correlator on disks, then check digit-per-digit. We can also do some A2A/Lanczos but this is a larger scale of things. That should be a rather strong check.

This is for the measurement part, HMC needs to be checked too but I guess you know better what to do there.

**Comment by paboyle** [comment]
I have closed feature/gpu-port back to develop. 
TeamCity and Travis are both clean.
HMC runs correctly on GPU.

It is very important that people developing code do a git pull and solve any conflicts.

If any conflicts is difficult to solve, you are likely better to get to a fresh develop and make your changes again, than to sort out the complexity of the GPU port changes into a dirty repository.

Note that "parallel_for" no longer exists and either thread_for or accelerator_for must be chosen.
