### ISSUE TITLE
Colors?

### ISSUE THREAD

**Issue by aportelli** [paboyle/Grid#25]
Hi,

Do we really want to do this colour thing? I see many cons:

1.  in a log file (which in production is always what we will be looking at) the special characters can mess up some text editors
2. the actual setup assume that the user have a white background, mine is black and running a Grid program will set my terminal to black text once then everything is unreadable and I have to kill my session

Pros: ??

Let me know what you think

**Comment by paboyle** [comment]
Yeah… I’ve taken it out already in my local version because I got annoyed with the special characters

Peter

> On 23 Feb 2016, at 16:46, Antonin Portelli <notifications@github.com> wrote:
> 
> Hi,
> 
> Do we really want to do this colours thing? I see many cons:
> 
> in a log file (which in production is always what we will be looking at) the special characters can mess up some text editors
> the actual setup assume that the user have a white background, mine is black and running a Grid program will set my terminal to black text once then everything is unreadable and I have to kill my session
> Pros: ??
> 
> Let me know what you think
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/paboyle/Grid/issues/25>.
> 


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by aportelli** [comment]
Ok good, so I guess it is alright if I remove it from the code?

**Comment by paboyle** [comment]
removal is committed.

**Comment by aportelli** [comment]
Ok cool thanks

**Comment by paboyle** [comment]
p.s. pro was to delineate in colour "Message/Warning/Error" which can make reading nicer. 
e.g. this is how Clang/Gcc colour their syntax warns.

But the color codes aren't sufficiently ubiquitous that it ports well enough

**Comment by aportelli** [comment]
Ok but that only works if you look at the program in live, from a computing node we will only have log files where no colour can be used.

**Comment by coppolachan** [comment]
I reopen this because the HMC still contains the coloring and it is not good for terminals with black background.
To be fixed.

**Comment by paboyle** [comment]
Closing issues -- I don't see the colouring in the HMC code. Can you identify the lines.

**Comment by coppolachan** [comment]
It is in my version, which is a bit behind. 
I modified the coloring adding classes that deal with this without using any static variable. 
Once the smearing branch is merged (I found few bugs in the ET in the process) I will integrate with the latest modifications.
