### ISSUE TITLE
Compiling for GPU

### ISSUE THREAD

**Issue by Marcel-Rodekamp** [paboyle/Grid#265]
Dear developers,
Are there any news on compiling for GPU compilation? I try to build Grid for NVIDIA Tesla V100 SXM2 32GB GPUs. 
I am currently working in the develop branch on
commit: 5d834486c928bf70fa69e83ddc7c4297216f7739
merge: b8bd8cd f7373e9

I have attached my configuration output obtained by the configure command:

`../configure --with-lime=/home/mrodekamp/LatticePrograms/Libraries/Lime CXX=nvcc CC=nvcc CXXFLAGS=-std=c++11 --enable-simd=GPU --prefix=/home/mrodekamp/LatticePrograms/Libraries/GridT/build`

I have further attached the output by `make -j` (make-j.out) and `make -j -C tests/ tests` (make-j-tests.out). I first did the `make -j` and then additionally the `make -j -C tests/ tests`.

I am using the nvcc:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

and devtools 7 including gcc 7.3.1:

gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

The libGrid.a is fully compiled but when I try to compile the tests some errors appear in
/Grid/qcd/smearing/GaugeConfiguration.h(222)

Can you tell me what I am doing wrong? I have tried the following before

    used devtools 8 (issues in the Hadrons folder)
    used CXX=nvcc in the configure but not CC=nvcc additionally
    not using the CXXFLAGS=-std=c++11 in both named devtools and CC/CXX ways

Please feel free to contact me if you require any more information.

Yours sincerely,

Marcel Rodekamp  

[make-j-tests.txt](https://github.com/paboyle/Grid/files/4214259/make-j-tests.txt)
[make-j.txt](https://github.com/paboyle/Grid/files/4214260/make-j.txt)
[grid.configure.summary.txt](https://github.com/paboyle/Grid/files/4214261/grid.configure.summary.txt)

**Comment by paboyle** [comment]
I'm using:

../configure --enable-comms=mpi --enable-simd=GPU CXX=nvcc CXXFLAGS=-ccbin mpicxx -gencode arch=compute_70,code=sm_70 -I/ccs/home/paboyle/prefix/includ
e/ -std=c++11 LDFLAGS=-L/ccs/home/paboyle/prefix/lib/ --prefix /ccs/home/paboyle/prefix --disable-openmp 

CUDA 10.1

**Comment by paboyle** [comment]
Hadrons does not build currently, but I think the tests do

**Comment by Marcel-Rodekamp** [comment]
Thanks for your advice. It now works perfectly fine. 
I actually don't need the Hadrons so that is fine for me, but they compiled (haven't tested if they run)
I ended up using 
`
../configure --enable-simd=GPU --enable-comms=mpi-auto CXX=nvcc MPICXX=mpic++ CXXFLAGS="-std=c++11  -arch=sm_70 -gencode=arch=compute_70,code=compute_70 -I/usr/local/openmpi/include -L/usr/local/openmpi/lib -lmpi" --with-lime=(user)/LatticePrograms/Libraries/Lime --enable-debug=no
`
