### ISSUE TITLE
fails to compile stout smearing

### ISSUE THREAD

**Issue by i-kanamori** [paboyle/Grid#286]
[grid.configure.summary.txt](https://github.com/paboyle/Grid/files/4632907/grid.configure.summary.txt)

Hello,

it seems a recent change https://github.com/paboyle/Grid/commit/2e652431e5248461d4fecb75b37b0b00fc40e405 causes a problem in compiling the stout smearing.  The constructor of the  SmearedConfiguration<Gimpl> tries to copy an argument to a member Smear_Stout<Gimpl> StoutSmearing (before it was a reference) but it fails because Smear_Stout<Gimpl> has a unique_ptr in the member.  My temporal hack is to change StoutSmearing to a pointer valued, though I don't think it on the right track.

Here is how to reproduce the error with tests/hmc/hmc_EOMobiusRatio

cd tests/hmc
make hmc_EOMobiusRatio
  CXX      Test_hmc_EOMobiusRatio.o
In file included from /nfshome/kanamori/work/Grid_tmp/Grid_develop/Grid/qcd/smearing/Smearing.h:6,
                 from /nfshome/kanamori/work/Grid_tmp/Grid_develop/Grid/Grid.h:46,
                 from ../../../tests/hmc/Test_hmc_EOMobiusRatio.cc:30:
/nfshome/kanamori/work/Grid_tmp/Grid_develop/Grid/qcd/smearing/GaugeConfiguration.h: In instantiation of 'Grid::SmearedConfiguration<Gimpl>::SmearedConfiguration(Grid::GridCartesian*, unsigned int, Grid::Smear_Stout<Gimpl>&) [with Gimpl = Grid::PeriodicGaugeImpl<Grid::GaugeImplTypes<Grid::Grid_simd<std::complex<double>, __vector(8) double>, 3> >]':
../../../tests/hmc/Test_hmc_EOMobiusRatio.cc:222:93:   required from here
/nfshome/kanamori/work/Grid_tmp/Grid_develop/Grid/qcd/smearing/GaugeConfiguration.h:222:69: error: use of deleted function 'Grid::Smear_Stout<Grid::PeriodicGaugeImpl<Grid::GaugeImplTypes<Grid::Grid_simd<std::complex<double>, __vector(8) double>, 3> > >::Smear_Stout(const Grid::Smear_Stout<Grid::PeriodicGaugeImpl<Grid::GaugeImplTypes<Grid::Grid_simd<std::complex<double>, __vector(8) double>, 3> > >&)'
       : smearingLevels(Nsmear), StoutSmearing(Stout), ThinLinks(NULL)
                                                                     ^
In file included from /nfshome/kanamori/work/Grid_tmp/Grid_develop/Grid/qcd/smearing/Smearing.h:5,
                 from /nfshome/kanamori/work/Grid_tmp/Grid_develop/Grid/Grid.h:46,
                 from ../../../tests/hmc/Test_hmc_EOMobiusRatio.cc:30:
/nfshome/kanamori/work/Grid_tmp/Grid_develop/Grid/qcd/smearing/StoutSmearing.h:40:7: note: 'Grid::Smear_Stout<Grid::PeriodicGaugeImpl<Grid::GaugeImplTypes<Grid::Grid_simd<std::complex<double>, __vector(8) double>, 3> > >::Smear_Stout(const Grid::Smear_Stout<Grid::PeriodicGaugeImpl<Grid::GaugeImplTypes<Grid::Grid_simd<std::complex<double>, __vector(8) double>, 3> > >&)' is implicitly deleted because the default definition would be ill-formed:
 class Smear_Stout : public Smear<Gimpl> {
       ^~~~~~~~~~~
/nfshome/kanamori/work/Grid_tmp/Grid_develop/Grid/qcd/smearing/StoutSmearing.h:40:7: error: use of deleted function 'std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = Grid::Smear<Grid::PeriodicGaugeImpl<Grid::GaugeImplTypes<Grid::Grid_simd<std::complex<double>, __vector(8) double>, 3> > >; _Dp = std::default_delete<Grid::Smear<Grid::PeriodicGaugeImpl<Grid::GaugeImplTypes<Grid::Grid_simd<std::complex<double>, __vector(8) double>, 3> > > >]'
In file included from /usr/include/c++/8/bits/locale_conv.h:41,
                 from /usr/include/c++/8/locale:43,
                 from /usr/include/c++/8/iomanip:43,
                 from /nfshome/kanamori/work/Grid_tmp/Grid_develop/Grid/GridStd.h:13,
                 from /nfshome/kanamori/work/Grid_tmp/Grid_develop/Grid/GridCore.h:44,
                 from /nfshome/kanamori/work/Grid_tmp/Grid_develop/Grid/Grid.h:41,
                 from ../../../tests/hmc/Test_hmc_EOMobiusRatio.cc:30:
/usr/include/c++/8/bits/unique_ptr.h:394:7: note: declared here
       unique_ptr(const unique_ptr&) = delete;
       ^~~~~~~~~~
make: *** [Makefile:875: Test_hmc_EOMobiusRatio.o] Error 1

**Comment by paboyle** [comment]
This might be a fix...

**Comment by paboyle** [comment]
in develop. will apply to sycl branch shortly

**Comment by paboyle** [comment]
Perhaps we can close as Isaaku verified the Smeared Link HMC again?

**Comment by i-kanamori** [comment]
works with the current develop, thank you very much.
