### ISSUE TITLE
LIME-less HMC tests fail due to LoadScidacCheckpointer

### ISSUE THREAD

**Issue by smangham** [paboyle/Grid#293]
I've recently tried building a simple version of Grid with no comms, double precision, AVX SIMD and HDF5. However, several of the HMC tests fail. Many don't pass due to #286, but `Test_hmc_WG_Production` and `Test_hmc_ScalarActionNxN` fail due to the error `HMCResourceManager has no member LoadScidacCheckpointer`. I'm assuming the Scidac functions comes from LIME, but I configured and built *without* LIME.

Not a blocker for me but still worth noting.

**Comment by paboyle** [comment]
Hi, 
Scidac software is required to use the Scidac file formats. If you want the HMC checkpoints to work and pass, you need the LIME library.
Best wishes,
Peter
