### ISSUE TITLE
Consider std::unordered_map instead of std::map in NerscField

### ISSUE THREAD

**Issue by mspraggs** [paboyle/Grid#3]
If you're always using C++11, then unordered_map may offer some performance improvements over std::map, since the best case lookup complexity is O(1) due to the underlying implementation using a hash table, and you're not iterating over header, so an ordered map isn't required.

On the other hand, loading an NERSC file is of course IO bound, so a few extra cycles spent using std::map probably won't affect things that much.

**Comment by paboyle** [comment]
Hi Matt, 
I don't think the header parsing is particularly performance critical, so I am happy to just use 
std::map since that is simpler to type!
