### ISSUE TITLE
Benchmarks can't build without LIME

### ISSUE THREAD

**Issue by smangham** [paboyle/Grid#315]
On a fresh install without LIME, the benchmark directory fails to build due to the error
```
/Grid/benchmarks/Benchmark_IO_vs_dir.cc:35:3: error: 'MSG' was not declared in this scope
   MSG << "Grid is setup to use " << threads << " threads" << std::endl;
   ^~~
```
And others like it. The `Benchmark_IO.hpp` file is in scope, but none of the contents can be found. It turns out that this is due to a  `#ifdef HAVE_LIME` at the very top of the file conditionalising all the content on LIME. As far as I can see, only the `limeWrite` and `limeRead` functions depend on LIME.

**Comment by paboyle** [comment]
Fixed now I think.
