### ISSUE TITLE
Benchmark_ITT - where is the throughput?

### ISSUE THREAD

**Issue by plvlnisse** [paboyle/Grid#320]
OK, I have to confess that I am a complete fool:
Where in the output do I find the CPU/GPU throughput number that is the "score" for evaluating the tenders?  :-)

**Comment by paboyle** [comment]
The score is at the end labelled:

```
==================================================================================
Grid : Message : 66.940572 s :  Comparison point     result: 1450617.641 Mflop/s per node
Grid : Message : 66.940583 s :  Comparison point is 0.5*(1371001.209+1530234.072) 
==================================================================================
```

The result is **1450617.641 Mflop/s per node**

**Comment by paboyle** [comment]
This was a single V100 GPU on Summit, for information.

**Comment by paboyle** [comment]
Again see:

https://github.com/paboyle/Grid/wiki/Benchmark_ITT:-Example-output

**Comment by paboyle** [comment]
closing
