### ISSUE TITLE
Benchmark_ITT - RFP conforming command line options?

### ISSUE THREAD

**Issue by plvlnisse** [paboyle/Grid#323]
Are vendors free to choose command line options to the benchmark codes? If not, what command line options are allowed and with what values?

**Comment by paboyle** [comment]
The vendors are not allowed to change the —mpi option in a manner inconsistent with the
procurement document.

The following may be added or modified:

—threads
—accelerator-threads 2/4/8
—shm 2048
--shm-hugepages

Communication options are varied internally by the benchmark, and the best result selected, so we believe 
there is no point to passing related options.

**Comment by paboyle** [comment]
--threads N

specifies thread count <= OMP_NUM_THREADS

and --accelerator-threads N  specifies how many threads run on each SM in Nvidia.

The number of threads per SM is 16 x N where the 16 is put into "coalesced" accesses, and residual subscription
factor on the SM "threadBlock" is a tuneable. N=2 or N=4 is typically best, but I set the default value to be the best option on Volta.

**Comment by MartinHilgeman** [comment]
You write that vendors are not allowed to change --mpi option, but there are no guidelines given for the optional runs on 2, 4, 8, 16 and 32 nodes.

**Comment by paboyle** [comment]
closing; (clearly --mpi had to change in the optional runs, sorry !).
