### ISSUE TITLE
Travis failing for Linux clang builds

### ISSUE THREAD

**Issue by aportelli** [paboyle/Grid#36]
The Travis build failing for Linux/clang come from the fact that LLVM guys closed their APT repository because network traffic was to heavy http://lists.llvm.org/pipermail/llvm-dev/2016-May/100303.html.
This is not surprising considering the increasing number of CI bots all downloading over and over again clang from their server.
Finding a plan B would be very painful, and some say this is just temporary and that the server will reopen.
I will keep a look on it and figure out something if it is not solved on LLVM side.

**Comment by paboyle** [comment]
Damned CI people should use a caching proxy.

**Comment by mspraggs** [comment]
So something I found Antonin which may be useful if you decide to go down the Vagrant route and build the packages yourself: Travis makes available the virtual machine used for their builds, and the one used by the currently failing build is at [this](https://github.com/travis-ci/travis-cookbooks/tree/a68419e) revision. They provide a Vagrantfile too, so it's relatively easy to start up the virtual machine and ssh in. Only problem is that llvm 3.8 requires gcc 4.9 to compile, so you'd need to install that from the Ubuntu toolchain PPA before you can build clang. This also means gcc 4.9 becomes a dependency, which is a bit frustrating. Anyway, good luck :-P

**Comment by aportelli** [comment]
I fixed the Travis Linux builds using clang. The test is failing but this is not a compilation issue so I will close this issue.
