### ISSUE TITLE
NERSC and ILDG files always claim to be SU(3)

### ISSUE THREAD

**Issue by edbennett** [paboyle/Grid#376]
Currently the [ILDG](https://github.com/paboyle/Grid/blob/cc094366a9b19f4bf4eb382658454d18cacacecf/Grid/parallelIO/IldgIO.h#L882) and [NERSC](https://github.com/paboyle/Grid/blob/cc094366a9b19f4bf4eb382658454d18cacacecf/Grid/parallelIO/NerscIO.h#L248) checkpointers always store the configuration type as `4D_SU3_GAUGE_3x3`. This means that when Grid is compiled for any gauge group other than SU(3), the configuration metadata does not correctly describe the data stored in the configuration, and also that downstream tooling (e.g. [GLU](https://github.com/RJHudspith/GLU)) fails to parse the configuration.

**Comment by RJHudspith** [comment]
This is an interesting point; I don't think either of the ILDG or NERSC configuration formats are standardized for NC!=3. In GLU I made the logical extension of these, i.e. changing SU3 to SU{whatever NC is compiled), similarly for the 4D part.

**Comment by RJHudspith** [comment]
Ok I created a pull request to address this, https://github.com/paboyle/Grid/pull/377
