### ISSUE TITLE
FMA support in clang++-3.8

### ISSUE THREAD

**Issue by james-simone** [paboyle/Grid#38]
Compiling Grid with clang++-3.8 and AVX2 support appears to trigger a compiler error related to FMA support in the intrinsics.

$ cd Grid
$ git rev-parse --short HEAD
5e02392

In file included from qcd/action/fermion/CayleyFermion5D.cc:31:
In file included from ./Grid.h:68:
In file included from ./Simd.h:166:
In file included from ./simd/Grid_vector_types.h:47:
./simd/Grid_avx.h:240:14: error: always_inline function '_mm256_fmaddsub_ps' requires target feature 'fma', but would be
      inlined into function 'operator()' that is compiled without support for 'fma'
      return _mm256_fmaddsub_ps( a_real, b, a_imag ); // Ar Br , Ar Bi   +- Ai Bi             = ArBr-AiBi , ArBi+AiBr
             ^
./simd/Grid_avx.h:286:14: error: always_inline function '_mm256_fmaddsub_pd' requires target feature 'fma', but would be
      inlined into function 'operator()' that is compiled without support for 'fma'
      return _mm256_fmaddsub_pd( a_real, b, a_imag ); // Ar Br , Ar Bi   +- Ai Bi             = ArBr-AiBi , ArBi+AiBr
             ^
fatal error: error in backend: Cannot select: 0x76cec80: v8f32 = X86ISD::FMADDSUB 0x787a1d0, 0x7a523a0, 0x7a52600

===== system details ========

$ cat /etc/redhat-release 
Scientific Linux release 7.2 (Nitrogen)

$ uname -a
Linux yosemite.fnal.gov 3.10.0-229.20.1.el7.x86_64 #1 SMP Wed Nov 4 10:08:36 CST 2015 x86_64 x86_64 x86_64 GNU/Linux

$ less /proc/cpuinfo
model name      : Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz

$ clang++ -v
clang version 3.8.0 (tags/RELEASE_380/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/james/installed/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64

$ ./configure CXX=clang++ CXXFLAGS="-std=c++11 -O3 -mavx2 -fopenmp -lomp" --enable-simd=AVX2

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Summary of configuration for grid v1.0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The following features are enabled:

- architecture (build)          : x86_64
- os (build)                    : linux-gnu
- architecture (target)         : x86_64
- os (target)                   : linux-gnu
- build DOXYGEN documentation   : no
- graphs and diagrams           : no
- Supported SIMD flags          :  -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx
----------------------------------------------------------
- enabled simd support          : AVX2   (config macro says supported: no )
- communications type           : none
- default precision             : double
- RNG choice                    : ranlux48
- LAPACK	                : no

**Comment by paboyle** [comment]
Hi Jim,

can you add -mfma to the Clang++ flags.

I think/suspect that clang is not supporting it by default when it does make sense that "avx2" should
include *all* of avx2.

On my haswell MacBook, I use clang 3.8:

 ../../configure --enable-precision=single --enable-simd=AVX2 CXXFLAGS=-mavx2 -mfma -O3 -std=c++11 -fopenmp LDFLAGS=-L/opt/llvm-3.8/lib/ LIBS=-lgmp -lmpfr -fopenmp --enable-comms=none CXX=/opt/llvm-3.8/bin/clang++

**Comment by paboyle** [comment]
any progress -- I know it is PR but I'd like to close issues before lattice conference ;)

**Comment by james-simone** [comment]
Hi Peter,

Sorry for the slow response! I followed you suggestion and the code compiles and runs.

	--jim

On 07/06/2016 04:56 PM, Peter Boyle wrote:
> any progress -- I know it is PR but I'd like to close issues before lattice conference ;)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/paboyle/Grid/issues/38#issuecomment-230919459>, or mute the
> thread <https://github.com/notifications/unsubscribe/AGIAzmVtGwIN1VoCsD5OkusFUuP5LO-1ks5qTCSMgaJpZM4JAOL5>.
>


-- 
--jim

**Comment by paboyle** [comment]
Thanks Jim,
closing.
