### ISSUE TITLE
Compilation errors and warnings build targeting Nvidia GPUs

### ISSUE THREAD

**Issue by james-simone** [paboyle/Grid#386]
I would appreciate any help building Grid for GPUs, details below.

Also, I wish to build 'Benchmark_ITT'. Should I use the develop branch, or another branch? 

1) Check that the code is pointing to the HEAD of develop

$ git log
commit 215df671be6ab6c53dce424ea1cd0cde803d97dd (grafted, HEAD -> develop, origin/
develop, origin/HEAD)

2) Give a description of the target platform (CPU, network, compiler).

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

$ cat /proc/cpuinfo | grep 'model name' | uniq
model name	: Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz

$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

$ nvcc --version
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0

3. Give the exact configure command used.

git clone --depth=1 --branch develop https://github.com/paboyle/Grid Grid
    cd /var/tmp/Grid
    source /opt/intel/mkl/bin/mklvars.sh intel64
    ./bootstrap.sh
    mkdir -p /var/tmp/Grid/build && cd /var/tmp/Grid/build &&  CXX=nvcc CXXFLAGS=" -std=c++14  -gencode arch=compute_70,code=sm_70  -I/usr/local/openmpi/include -I/usr/local/fftw/include -I/usr/local/hdf5/include -I/usr/local/scidac/include"  LDFLAGS=" -L/usr/local/openmpi/lib     -L/usr/local/fftw/lib     -L/usr/local/hdf5/lib     -L/usr/local/scidac/lib"  LIBS=-lmpi MPICXX=mpicxx /var/tmp/Grid/configure --prefix=/usr/local/grid --enable-accelerator=cuda --enable-comms=mpi3-auto --enable-mkl=yes --enable-openmp --enable-simd=GPU

5. Attach grid.config.summary
$ cat grid.configure.summary
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Summary of configuration for Grid v0.7.0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
----- GIT VERSION -------------------------------------
commit: 215df67
branch: develop
date  : 2022-02-01
----- PLATFORM ----------------------------------------
architecture (build)        : x86_64
os (build)                  : linux-gnu
architecture (target)       : x86_64
os (target)                 : linux-gnu
compiler vendor             : gnu
compiler version            :
----- BUILD OPTIONS -----------------------------------
Nc                          : 3
SIMD                        : GPU (width= 64)
Threading                   : yes
Acceleration                : cuda
Unified virtual memory      : yes
Communications type         : mpi3
Shared memory allocator     : no
Shared memory mmap path     : /var/lib/hugetlbfs/global/pagesize-2MB/
Default precision           :
Software FP16 conversion    : yes
RNG choice                  : sitmo
GMP                         : yes
LAPACK                      : no
FFTW                        : yes
LIME (ILDG support)         : yes
HDF5                        : yes
build DOXYGEN documentation : no
----- BUILD FLAGS -------------------------------------
CXXFLAGS:
    -I/var/tmp/Grid
    -O3
    -std=c++14
    -gencode
arch=compute_70,code=sm_70
    -I/usr/local/openmpi/include
    -I/usr/local/fftw/include
    -I/usr/local/hdf5/include
    -I/usr/local/scidac/include
    -Xcompiler
    -fno-strict-aliasing
    --expt-extended-lambda
    --expt-relaxed-constexpr
    -Xcompiler
    -fopenmp
LDFLAGS:
    -L/var/tmp/Grid/build/Grid
    -L/usr/local/openmpi/lib
    -L/usr/local/fftw/lib
    -L/usr/local/hdf5/lib
    -L/usr/local/scidac/lib
    -Xcompiler
    -fopenmp
LIBS:
    -lhdf5_cpp
    -lz
    -lcrypto
    -llime
    -lmpfr
    -lgmp
    -lmkl_rt
    -lstdc++
    -lm
    -lmpi
    -lcuda
    -lz
    -lhdf5
-------------------------------------------------------

6. Attach the output of make V=1

nvcc -x cu  -DHAVE_CONFIG_H -I. -I/var/tmp/Grid/Grid    -I/var/tmp/Grid     -O3  -std=c++14  -gencode arch=compute_70,code=sm_70  -I/usr/local/openmpi/include -I/usr/local/fftw/include -I/usr/local/hdf5/include -I/usr/local/scidac/include  -Xcompiler -fno-strict-aliasing --expt-extended-lambda --expt-relaxed-constexpr -Xcompiler -fopenmp -MT qcd/action/fermion/instantiation/GparityWilsonImplD/CompactWilsonCloverFermionInstantiationGparityWilsonImplD.o -MD -MP -MF $depbase.Tpo -c -o qcd/action/fermion/instantiation/GparityWilsonImplD/CompactWilsonCloverFermionInstantiationGparityWilsonImplD.o /var/tmp/Grid/Grid/qcd/action/fermion/instantiation/GparityWilsonImplD/CompactWilsonCloverFermionInstantiationGparityWilsonImplD.cc &&\
mv -f $depbase.Tpo $depbase.Po
/var/tmp/Grid/Grid/DisableWarnings.h(47): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

/var/tmp/Grid/Grid/DisableWarnings.h(48): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

/var/tmp/Grid/Grid/DisableWarnings.h(51): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

/var/tmp/Grid/Grid/DisableWarnings.h(52): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

/var/tmp/Grid/Grid/Grid_Eigen_Dense.h(17): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

/var/tmp/Grid/Grid/qcd/action/fermion/implementation/CompactWilsonCloverFermionImplementation.h(50): error: class "Grid::GparityWilsonImplParams" has no member "boundary_phases"
          detected during instantiation of "Grid::CompactWilsonCloverFermion<Impl>::CompactWilsonCloverFermion(Grid::CompactWilsonCloverFermion<Impl>::GaugeField &, Grid::GridCartesian &, Grid::GridRedBlackCartesian &, Grid::RealD, Grid::RealD, Grid::RealD, Grid::RealD, const Grid::WilsonAnisotropyCoefficients &, const Grid::CompactWilsonCloverFermion<Impl>::ImplParams &) [with Impl=Grid::GparityWilsonImplD]"
/var/tmp/Grid/Grid/qcd/action/fermion/instantiation/GparityWilsonImplD/CompactWilsonCloverFermionInstantiationGparityWilsonImplD.cc(39): here

/var/tmp/Grid/Grid/qcd/action/fermion/WilsonCloverHelpers.h(266): error: no instance of overloaded function "Grid::iVector<vtype, N>::operator() [with vtype=Grid::iVector<Grid::iVector<Grid::Complex, 3>, 4>, N=2]" matches the argument list
            object type is: CalcSpinor
          detected during:
            instantiation of "void Grid::CompactWilsonCloverHelpers<Impl>::MooeeKernel_gpu(int, int, const Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
(505): here
            instantiation of "void Grid::CompactWilsonCloverHelpers<Impl>::MooeeKernel(int, int, const Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
/var/tmp/Grid/Grid/qcd/action/fermion/implementation/CompactWilsonCloverFermionImplementation.h(285): here
            instantiation of "void Grid::CompactWilsonCloverFermion<Impl>::MooeeInternal(const Grid::CompactWilsonCloverFermion<Impl>::FermionField &, Grid::CompactWilsonCloverFermion<Impl>::FermionField &, const Grid::CompactWilsonCloverFermion<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverFermion<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
/var/tmp/Grid/Grid/qcd/action/fermion/implementation/CompactWilsonCloverFermionImplementation.h(137): here

/var/tmp/Grid/Grid/qcd/action/fermion/WilsonCloverHelpers.h(266): error: no instance of overloaded function "Grid::iVector<vtype, N>::operator() [with vtype=Grid::iVector<Grid::iVector<Grid::Complex, 3>, 4>, N=2]" matches the argument list
            object type is: CalcSpinor
          detected during:
            instantiation of "void Grid::CompactWilsonCloverHelpers<Impl>::MooeeKernel_gpu(int, int, const Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
(505): here
            instantiation of "void Grid::CompactWilsonCloverHelpers<Impl>::MooeeKernel(int, int, const Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
/var/tmp/Grid/Grid/qcd/action/fermion/implementation/CompactWilsonCloverFermionImplementation.h(285): here
            instantiation of "void Grid::CompactWilsonCloverFermion<Impl>::MooeeInternal(const Grid::CompactWilsonCloverFermion<Impl>::FermionField &, Grid::CompactWilsonCloverFermion<Impl>::FermionField &, const Grid::CompactWilsonCloverFermion<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverFermion<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
/var/tmp/Grid/Grid/qcd/action/fermion/implementation/CompactWilsonCloverFermionImplementation.h(137): here

/var/tmp/Grid/Grid/qcd/action/fermion/WilsonCloverHelpers.h(266): error: no instance of overloaded function "Grid::iVector<vtype, N>::operator() [with vtype=Grid::iVector<Grid::iVector<Grid::Complex, 3>, 4>, N=2]" matches the argument list
            object type is: CalcSpinor
          detected during:
            instantiation of "void Grid::CompactWilsonCloverHelpers<Impl>::MooeeKernel_gpu(int, int, const Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
(505): here
            instantiation of "void Grid::CompactWilsonCloverHelpers<Impl>::MooeeKernel(int, int, const Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
/var/tmp/Grid/Grid/qcd/action/fermion/implementation/CompactWilsonCloverFermionImplementation.h(285): here
            instantiation of "void Grid::CompactWilsonCloverFermion<Impl>::MooeeInternal(const Grid::CompactWilsonCloverFermion<Impl>::FermionField &, Grid::CompactWilsonCloverFermion<Impl>::FermionField &, const Grid::CompactWilsonCloverFermion<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverFermion<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
/var/tmp/Grid/Grid/qcd/action/fermion/implementation/CompactWilsonCloverFermionImplementation.h(137): here

/var/tmp/Grid/Grid/qcd/action/fermion/WilsonCloverHelpers.h(266): error: no instance of overloaded function "Grid::iVector<vtype, N>::operator() [with vtype=Grid::iVector<Grid::iVector<Grid::Complex, 3>, 4>, N=2]" matches the argument list
            object type is: CalcSpinor
          detected during:
            instantiation of "void Grid::CompactWilsonCloverHelpers<Impl>::MooeeKernel_gpu(int, int, const Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
(505): here
            instantiation of "void Grid::CompactWilsonCloverHelpers<Impl>::MooeeKernel(int, int, const Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
/var/tmp/Grid/Grid/qcd/action/fermion/implementation/CompactWilsonCloverFermionImplementation.h(285): here
            instantiation of "void Grid::CompactWilsonCloverFermion<Impl>::MooeeInternal(const Grid::CompactWilsonCloverFermion<Impl>::FermionField &, Grid::CompactWilsonCloverFermion<Impl>::FermionField &, const Grid::CompactWilsonCloverFermion<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverFermion<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
/var/tmp/Grid/Grid/qcd/action/fermion/implementation/CompactWilsonCloverFermionImplementation.h(137): here

/var/tmp/Grid/Grid/qcd/action/fermion/WilsonCloverHelpers.h(266): error: no instance of overloaded function "Grid::iVector<vtype, N>::operator() [with vtype=Grid::iVector<Grid::iVector<Grid::Complex, 3>, 4>, N=2]" matches the argument list
            object type is: CalcSpinor
          detected during:
            instantiation of "void Grid::CompactWilsonCloverHelpers<Impl>::MooeeKernel_gpu(int, int, const Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
(505): here
            instantiation of "void Grid::CompactWilsonCloverHelpers<Impl>::MooeeKernel(int, int, const Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, Grid::CompactWilsonCloverHelpers<Impl>::FermionField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverHelpers<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
/var/tmp/Grid/Grid/qcd/action/fermion/implementation/CompactWilsonCloverFermionImplementation.h(285): here
            instantiation of "void Grid::CompactWilsonCloverFermion<Impl>::MooeeInternal(const Grid::CompactWilsonCloverFermion<Impl>::FermionField &, Grid::CompactWilsonCloverFermion<Impl>::FermionField &, const Grid::CompactWilsonCloverFermion<Impl>::CloverDiagonalField &, const Grid::CompactWilsonCloverFermion<Impl>::CloverTriangleField &) [with Impl=Grid::GparityWilsonImplD]"
/var/tmp/Grid/Grid/qcd/action/fermion/implementation/CompactWilsonCloverFermionImplementation.h(137): here

6 errors detected in the compilation of "/var/tmp/Grid/Grid/qcd/action/fermion/instantiation/GparityWilsonImplD/CompactWilsonCloverFermionInstantiationGparityWilsonImplD.cc".

**Comment by fjosw** [comment]
The most recent version of develop does not compile, see #383. The errors you are seeing are related to this issue.

You could either disable gparity and additional fermion representation as described in #383, roll back to commit 135808dcfa767edf988976ae31d2876bb6389f8b or wait for a fix.

**Comment by james-simone** [comment]
I used branch [135808d](https://github.com/paboyle/Grid/commit/135808dcfa767edf988976ae31d2876bb6389f8b) and the build worked.
