### ISSUE TITLE
Benchmark_dwf* fails in branch develop

### ISSUE THREAD

**Issue by coppolachan** [paboyle/Grid#39]
As per the title. I'm now in the stage of merging the smearing branch and I'm retesting everything, but not have the time to address immediately this issue. If someone wants to solve it in the meantime...
It was running in my branch before the merge

My configuration flags
../../Grid/configure --enable-precision=single --enable-simd=AVX CXXFLAGS=-mavx -fopenmp=libomp -O3 -std=c++11 LDFLAGS=-fopenmp=libomp LIBS=-lgmp -lmpfr --enable-comms=none

**Comment by aportelli** [comment]
Hi Guido from what I can see the `develop` branch is fine (https://travis-ci.org/paboyle/Grid/builds/141859994) the failed build is on your merge branch so it might up to you to correct this?

**Comment by coppolachan** [comment]
Hi Antonin, I switched to the develop branch to test exactly this, because it was failing on my merge.

The build is ok, is the executable that fails.

**Comment by paboyle** [comment]
The executable Benchmark_dwf *IS* tested in the build on travis, and I agree that Guido appears to have
broken it by removing the patch that I put in that fixed it.

Travis Log prior to Guido's commit:

https://travis-ci.org/paboyle/Grid/builds/141859994

$ ./benchmarks/Benchmark_dwf --threads 1
Grid     : Warning     : 0      ms : '--threads' option used but Grid was not compiled with thread support
__|__|__|__|__|__|__|__|__|__|__|__|__|__|__
__|__|__|__|__|__|__|__|__|__|__|__|__|__|__
__|_ |  |  |  |  |  |  |  |  |  |  |  | _|__
__|_                                    _|__
__|_    GGGG    RRRR    III    DDDD     _|__
__|_   G        R   R    I     D   D    _|__
__|_   G        R   R    I     D    D   _|__
__|_   G  GG    RRRR     I     D    D   _|__
__|_   G   G    R  R     I     D   D    _|__
__|_    GGGG    R   R   III    DDDD     _|__
__|_                                    _|__
__|__|__|__|__|__|__|__|__|__|__|__|__|__|__
__|__|__|__|__|__|__|__|__|__|__|__|__|__|__
  |  |  |  |  |  |  |  |  |  |  |  |  |  |  
Copyright (C) 2015 Peter Boyle, Azusa Yamaguchi, Guido Cossu, Antonin Portelli and other authors
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
Grid     : Message     : 25     ms : Grid is setup to use 1 threads
Grid     : Message     : 25     ms : Making s innermost grids
Grid     : Message     : 25     ms : Making s innermost rb grids
Grid     : Message     : 2449   ms : Calling Dw
Grid     : Message     : 2659   ms : Called Dw 10 times in 208498 us
Grid     : Message     : 2662   ms : norm result 1.95449e+07
Grid     : Message     : 2666   ms : norm ref    1.95449e+07
Grid     : Message     : 2670   ms : mflop/s =   4224.52
Grid     : Message     : 2672   ms : mflop/s per node =  4224.52
Grid     : Message     : 2685   ms : norm diff   6.68005e-25
Grid     : Message     : 3107   ms : Called Dw sinner 10 times in 230982 us
Grid     : Message     : 3109   ms : mflop/s =   3813.3
Grid     : Message     : 3109   ms : mflop/s per node =  3813.3
 difference between normal and simd is 0
Grid     : Message     : 3352   ms : EO src norm diff   0
Grid     : Message     : 3472   ms : sDeo mflop/s =   4013.47
Grid     : Message     : 3474   ms : sDeo mflop/s per node   4013.47
Grid     : Message     : 3560   ms : sE norm diff   0
Grid     : Message     : 3566   ms : sO norm diff   0
Grid     : Message     : 3744   ms : Called DwDag
Grid     : Message     : 3746   ms : norm result 1.95238e+07
Grid     : Message     : 3750   ms : norm ref    1.95238e+07
Grid     : Message     : 3759   ms : norm diff   4.81804e-25
Grid     : Message     : 3767   ms : Calling Deo and Doe
Grid     : Message     : 3809   ms : src_e261804
Grid     : Message     : 3812   ms : src_o262391
Grid     : Message     : 3917   ms : Deo mflop/s =   4306.86
Grid     : Message     : 3919   ms : Deo mflop/s per node   4306.86
Grid     : Message     : 3968   ms : r_e9.78579e+06
Grid     : Message     : 3969   ms : r_o9.75908e+06
Grid     : Message     : 3970   ms : res1.95449e+07
Grid     : Message     : 4063   ms : norm diff   0
Grid     : Message     : 4107   ms : norm diff even  0
Grid     : Message     : 4110   ms : norm diff odd   0

for example.

This fails in Guido's commit:

https://travis-ci.org/paboyle/Grid/jobs/142254863

**Comment by paboyle** [comment]
For what it is worth, the patch was in

lib/qcd/actions/fermion/WilsonKernels.cc 

to disable the call to assembler unless AVX512 is set.

It was already in develop for some days.

**Comment by coppolachan** [comment]
Fails also with only 1 thread.

I have no commits in the branch develop.

**Comment by paboyle** [comment]
Can you post the precise nature of the fail & also try with SSE4 ?

I don't understand how this is consistent with the travis compile of develop passing (which uses SSE4 since the VM's dont guarantee to have AVX and beyond - possible an AVX only issue though)

**Comment by coppolachan** [comment]
My bad, the branch I checked out was updated to June.
After the full update, it is working. 
Sorry for taking you time.
