### ISSUE TITLE
Milestones?

### ISSUE THREAD

**Issue by aportelli** [paboyle/Grid#45]
I have started adding the '0.6.0' milestone to some issues. I think this system is useful to plan releases. Tell me if you think it is inconvenient.

**Comment by paboyle** [comment]
Where do we centrally collate/query  all the work we think is needed for 0.6.0 ?

I agree that organisation is good -- just don't see where I browse the work list and process.

**Comment by aportelli** [comment]
There are many way to do that, you can just click on the "milestone" button in the main issue menu. In the issue filters you can select only issues corresponding to one milestone. Finally, if you are browsing an issue which is flagged with a milestone then you can see the milestone progress on the right and click on it to see the corresponding issues. I hope that helps

**Comment by paboyle** [comment]
Leaving what I would view as desirable for v0.6.0

-- FFT

-- Gamma rework to complete basis, work with Antonin on meson trace code to make
    it look pretty.

-- Doxygen avalable online somehow

-- Clean up mixed precision

-- Thread safe & threaded version of code in Lattice_transfer

-- Check for no call of peek/poke from threaded regions

-- Optimised precision changing

-- Assembly "Ddag" in KNL 

-- Generic fermion reps

-- Applications directory and common HMC, RHMC

-- Move Lanczos to use Eigen matrix types. Replace "DenseMatrix" with Eigen types.

-- PAB to audit core code (lib, but not down lib/qcd tree).

**Comment by aportelli** [comment]
Thanks for the list it is nice to have a roadmap. We are now ~100 commits since 0.5.1 and important changes have been made. I thought that maybe it would be good to release 0.6 rather soon (i.e. in the next 2 weeks)? Many of the features you listed can represent a significant amount of time and could constitue good goals for the next version. I would suggest:

**0.6:**
- Doxygen avalable online somehow
- PAB to audit core code (lib, but not down lib/qcd tree)

**0.7:**
- FFT
- Gamma rework to complete basis, work with Antonin on meson trace code to make it look pretty
- Clean up mixed precision
- Thread safe & threaded version of code in Lattice_transfer
- Check for no call of peek/poke from threaded regions
- Optimised precision changing
- Assembly "Ddag" in KNL
- Generic fermion reps
- Applications directory and common HMC, RHMC
- Move Lanczos to use Eigen matrix types. Replace "DenseMatrix" with Eigen types.

What do you think?

**Comment by aportelli** [comment]
Just to keep track of things, I have started adding things to do for the first "final" version (1.0).

**Comment by paboyle** [comment]
I'm worried that we will run into 1.0 too soon.... 

I'd vote for 0.5.3 quickly and the extended features in a 0.6.0 ?

Doesn't change the practice, but numbering would leave me more comfortable.

**Comment by aportelli** [comment]
That sounds good. My point was just on trying to have regular checkpointing of versions we think are usable, keeping `master` alive. I don't have a strong opinion on the numbering scheme.

**Comment by aportelli** [comment]
Hi I just want to keep this issue alive, we are slowly going into not releasing versions, `master` is totally outdated now. Shall we push onto releasing 0.6.0?
