### ISSUE TITLE
File formats support

### ISSUE THREAD

**Issue by coppolachan** [paboyle/Grid#52]
Add new file formats: 
- ILDG is needed 
- Some people from US suggested/requested HDF5
- other suggestions?

**Comment by paboyle** [comment]
Agree both ILDG and HDF5. Just haven't had the time.

Not a format, but option to make use of MPI-2 IO .

Other people work on performance and we should use it.

**Comment by paboyle** [comment]
Need to cover MPI-2 I/O. Suggets using a lexicon non-simd grid (similar to the FFT code) and calling
local convert.

**Comment by paboyle** [comment]
We should split this into to issues;

ILDG for 0.8.0

Resubmit a new one for 1.0.0
-- HDF5 ; we need community consensus on metadata, internal structure.
     Minimally include everything in ILDG in a sensible layout.
     Are there preexisting HDF5 formats people are using?

-- MPI2 IO

**Comment by paboyle** [comment]
didn't mean to close.

**Comment by paboyle** [comment]
Can close this. Support Scidac, ILDG and use high performance MPI2-IO in the binary reader now.
