### ISSUE TITLE
Travis test failure on XCODE5

### ISSUE THREAD

**Issue by coppolachan** [paboyle/Grid#53]
Travis on XCODE 5 continues to fail due to the time it takes to compile in the virtual machine.
I tried to separate the matrix of computations splitting the single and double but without success. The env options inside the `matrix:` seem not to allow for splitting the compilations and external `env:` will be overridden. 
Any ideas?

**Comment by paboyle** [comment]
annoys the hell out of me too. We are doing several builds in one, and splitting clearly right
thing. Haven't seen easily how to though, but didn't really try yet to be honest.

**Comment by aportelli** [comment]
It's seems that it is going through now. Maybe they upgraded their VM to something faster. I'll close that, we can reopen the issue if the problem comes back.

**Comment by coppolachan** [comment]
Reopen this, 'cause it looks that the problem is not gone, see the failure of my last commit
https://travis-ci.org/paboyle/Grid/builds/164965163

**Comment by aportelli** [comment]
Aaaaaah. Ok but it looks different, the job didn't run out of time but was killed because it stalled for more than 10 min. I restarted it, maybe we were just unlucky.

**Comment by coppolachan** [comment]
it is not the first time I see the Xcode5 gcc version stalling in this way. Not sure why it is happening only for the gcc compilation, the VM should be the same as for the clang compilation.

**Comment by aportelli** [comment]
It passed, it looked like it was just an accident. Let's see how it goes from here.

**Comment by coppolachan** [comment]
good, 
let's monitor for few more commits.

**Comment by paboyle** [comment]
Following discussion with Guido today I dropped the MacOS GCC build.

We test: 
MacOS and Ubuntu

GCC (2 versions) and Clang.

The OS varies the sys headers, but these need not be varied against both compilers.

Of course, if the MacOS / gcc were reliable I would include it, but think on balance that
doing both OS's and all three compilers on Linux is sufficient.
