### ISSUE TITLE
--enable-lapack flag problems

### ISSUE THREAD

**Issue by azrael417** [paboyle/Grid#55]
It seems that the configure flag --enable-lapack just checks if liblapack is there. However, it would be good if it also checks if MKL is there and continue if this is the case. Maybe by test-compiling a small file which makes a lapack call with and without trailing underscores and if one of it succeeds, just continue.

**Comment by aportelli** [comment]
Hi. I am not so keen on going down the road of testing platform specific libraries like the MKL. Especially that the MKL can be configured linked in numerous different ways. However what I can do (and have already done with other libraries) is to add an option `--with-lapack-name=` to allow to change the name of lapack (e.g. to `mkl_core`). I'll look into that.

**Comment by paboyle** [comment]
We also need to be able to distinguish between MKL fftw wrappers and fftw itself in the build selection.

**Comment by aportelli** [comment]
Hi Peter, yes I will set all that clean when I will have my workstation with all the Intel software

**Comment by aportelli** [comment]
Hi Thorsten,

I have been trying to change all kind of things in the build system to address automatically some of the issues you have been filling. Could you please help me check that everything is ok?
Could you please check out our release candidate branch `release/v.0.6.0` and follow the instructions in the [updated README file](https://github.com/paboyle/Grid/blob/release/v0.6.0/README.md) and let me know if Grid configures and compiles fine without you needing to tweak any extra environment variables?

**Comment by aportelli** [comment]
Hi again Thorsten.

We are trying to close issues related to v0.6 in order to release. Could you please confirm that this issue is solved for you?

**Comment by azrael417** [comment]
Hi Antonin, I will come back to that today, sorry for the delay.
