### ISSUE TITLE
Building Grid on machine with AMD porcessors

### ISSUE THREAD

**Issue by witzel** [paboyle/Grid#56]
Hi,
I built Grid for the Bc-cluster at Fermilab (AMD Opteron 6320) using icc v16 with impi 5.1.3. No issues when building but when executing the binary only the following message is printed:

Please verify that both the operating system and the processor support Intel(R) X87, CMOV, MMX, FXSAVE, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT and AVX instructions.

Allowed flags from /proc/cpuinfo
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nonstop_tsc extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold bmi1

Outputs from configure and make (config.log, config.out) are attached. I'm mainly testing the configure script and cleaning-up my install. 
CXX=icpc  ../Grid/configure --enable-simd=AVX  --enable-comms=mpi-auto

I have a working build using the same intel compilers on this machine. However, that was created by explicitly specifying compile options on September 26, 2016 (cf config.log-2016-09-26).

Thank you,
Oliver
PS: To upload files I attached suffix '.txt' to the filename.

[config.log.txt](https://github.com/paboyle/Grid/files/513770/config.log.txt)
[config.log-2016-09-26.txt](https://github.com/paboyle/Grid/files/513768/config.log-2016-09-26.txt)
[config.out.txt](https://github.com/paboyle/Grid/files/513769/config.out.txt)

**Comment by aportelli** [comment]
Hi Oliver, can you please build with other instruction sets and see which ones are succeeding? I would try SSE and the generic code.

**Comment by witzel** [comment]
Hi Antonin,

I've followed your suggestion and tried configuring / compiling Grid with different simd options on this machine. While GEN works, SSE4 does not; the binary only reports a message like above. Going back to the AVX option, I get around the problem by only adding CXXFLAGS="-mavx" i.e.
CXX=icpc ../Grid/configure --enable-simd=AVX CXXFLAGS="-mavx"  --enable-comms=mpi-auto

Except for explicit '-mavx', both config.log files are equal. I don't see what the explicit '-mavx' is forcing but it seems to be necessary for icpc v16 on an AMD chip. -- It's not on an intel chip.

Thanks,
Oliver

**Comment by aportelli** [comment]
Hi Oliver can I have the confit log and output for the working case please?

**Comment by witzel** [comment]
Sorry, didn't notice that github refused my files because of the unknown suffix.
Oliver
[config.log-AVX.txt](https://github.com/paboyle/Grid/files/516233/config.log-AVX.txt)
[config.out-AVX.txt](https://github.com/paboyle/Grid/files/516232/config.out-AVX.txt)

**Comment by aportelli** [comment]
Ok I got it, from the Intel Compiler doc the `-x` options are only supported by Intel compilers. Then the order of flags matters, so when you pu `-mavx` at the end it takes over `-xavx`. I'll find a way to fine-tune the configure scripts and have a target for AMD. Could you please send me the exact model reference of this AMD CPU? What machine is that?

**Comment by aportelli** [comment]
Ok the model is in your original post so don't worry about it.

**Comment by aportelli** [comment]
The CPU you are using is supporting FMA instructions so you should definitely use them. I have committed a little fix. Please update `develop` on your machine and configure using `--with-simd=AVXFMA4` and please confirm to me that it worked.

On a different note, I am not entirely sure how good the Intel compiler is to generate the FMA4 instructions specific to AMD platforms. You might want to compare performances with clang and GCC (still using `--with-simd=AVXFMA4`).

**Comment by witzel** [comment]
Thank you, Antonin. Intel is not happy when using --enable-simd=AVXFMA4; the code does not compile first printing
icpc: command line warning #10353: option '-mfma' ignored, suggest using '-march=core-avx2'
and then errors
n file included from /project/fourpluseight/GRID/Grid/include/Grid/simd/Grid_vector_types.h(48),
                 from /project/fourpluseight/GRID/Grid/include/Grid/Simd.h(175),
                 from ../../Grid/lib/Grid.h(68),
                 from ../../Grid/lib/PerfCount.cc(29):
/project/fourpluseight/GRID/Grid/include/Grid/simd/Grid_avx.h(234): error: identifier "_mm256_maddsub_ps" is undefined
        return _mm256_maddsub_ps( a_real, b, a_imag ); // Ar Br , Ar Bi   +- Ai Bi             = ArBr-AiBi , ArBi+AiBr

Full output is attached.
[config.log.AVFFMA4.txt](https://github.com/paboyle/Grid/files/519370/config.log.AVFFMA4.txt)
[config.out.AVFFMA4.txt](https://github.com/paboyle/Grid/files/519369/config.out.AVFFMA4.txt)
[make.out.AVFFMA4.txt](https://github.com/paboyle/Grid/files/519368/make.out.AVFFMA4.txt)

I also tried compiling --enable-simd=AVXFMA4 using gcc 4.9.1 but likewise couldn't build Grid.  
[config.log.gcc.AVFFMA4.txt](https://github.com/paboyle/Grid/files/519389/config.log.gcc.AVFFMA4.txt)
[config.out.gcc.AVFFMA4.txt](https://github.com/paboyle/Grid/files/519387/config.out.gcc.AVFFMA4.txt)
[make.out.gcc.AVFFMA4.txt](https://github.com/paboyle/Grid/files/519388/make.out.gcc.AVFFMA4.txt)

**Comment by coppolachan** [comment]
I'll add here that the CPU supports FMA but not FMA4, just FMA3. 
-mfma should be enough using GCC but it seems that it is still looking for fma4 functions even with the `-mavx -mfma` 
The configure.ac is using fma4 for the generic clang gnu compilation

GCC supports FMA4 with -mfma4 since version 4.5.0[15] and FMA3 with -mfma since version 4.7.0.

**Comment by coppolachan** [comment]
Oliver, would you try the last commit in develop?
I added another SIMD type: AVXFMA that should work for gnu compilation.
G

**Comment by aportelli** [comment]
Hi Guido, where is that coming from? The Opteron 6320 does support FMA4 (Piledriver arch).

**Comment by coppolachan** [comment]
You are right.

There is a suspicious line in the Grid_avx.h
`#if defined (AVX2) || defined (AVXFMA4) 
#define _mm256_alignr_epi32(ret,a,b,n) ret=(__m256) _mm256_alignr_epi8((__m256i)a,(__m256i)b,(n*4)%16)
#define _mm256_alignr_epi64(ret,a,b,n) ret=(__m256d) _mm256_alignr_epi8((__m256i)a,(__m256i)b,(n*8)%16)
#endif`

the `_mm256_alignr_epi8` is not an FMA4 function, only AVX2. Then the compiler complaining about a target mismatch: asking for an AVX2 function but with an -mavx flag. 

Why the ` || defined (AVXFMA4) ` is there? 
I did not delete in the commit with the fix because I first would like to know if there was a compelling reason.
G

**Comment by witzel** [comment]
Thank you, Guido. gcc compiles fine using --enable-simd=AVXFMA and also runs without issues.

Knowing icpc is not favoured on AMD chips, I gave it a try. At compile time I get the warnings
icpc: command line warning #10353: option '-mfma' ignored, suggest using '-march=core-avx2'
and found on 'man icc' that intel is by default using '-fma'. Anyhow, I get a binary which starts but it crashes after reporting nan:

Grid : Message        : 3 ms : Grid is setup to use 16 threads
Grid : Message        : 239 ms : MobiusFermion (b=1.5,c=0.5) with Ls= 12 Tanh approx
Grid : Message        : 303 ms : Filling the smeared set
Grid : Message        : 303 ms : [HMC parameter] Trajectories            : 1
Grid : Message        : 303 ms : [HMC parameter] Start trajectory        : 0
Grid : Message        : 304 ms : [HMC parameter] Metropolis test (on/off): 1
Grid : Message        : 304 ms : [HMC parameter] Thermalization trajs    : 10
Grid : Message        : 304 ms : -- # Trajectory = 0
Grid : Message        : 1150 ms : Momentum action H_p = -nan
Test_BSM10f_sMDWF_SymanzikGauge: /project/fourpluseight/GRID/Grid/include/Grid/algorithms/iterative/ConjugateGradient.h:66: void Grid::ConjugateGradient<Field>::operator()(Grid::LinearOperatorBase<Field> &, const Field &, Field &) [with Field = Grid::Lattice<Grid::iScalar<Grid::iVector<Grid::iVector<Grid::Grid_simd<std::complex<double>, __m256d>, 3>, 4>>>]: Assertion `std::isnan(guess) == 0' failed.
Aborted

I guess __m256d again hints at avx2? Maybe AVXFMA shoud not be permitted for intel compilers or downgraded to AVX by the configure script?

**Comment by coppolachan** [comment]
mm256 type is for AVX and AVX2. I should investigate on this with an intel compiler. Btw the problem seems wrong instructions executed because the nan results from a computation (a simple sum...).

**Comment by aportelli** [comment]
@coppolachan: that's a good spot, let's remember to ask Peter tomorrow. We should be able to make `AVXFMA4` on that platform and it looks like this is the problem.
@witzel: `_m256d` is no AVX2 but is just an AVX 256bit vector. From the discussion today, it sounds clear to me that we are not going to provide support for Intel compiler on AMD platforms. So as far as this issue is concerned, let us focus only on GCC.
