### ISSUE TITLE
Shared memory buffers allocated even with standard MPI comms

### ISSUE THREAD

**Issue by giltirn** [paboyle/Grid#67]
I am running on Cori and it crashed with the error:

> NOARCH.splanc.x: ../../../src/Grid/lib/communicator/Communicator_base.cc:49: void *Grid::CartesianCommunicator::ShmBufferMalloc(unsigned long): Assertion heap_bytes<MAX_MPI_SHM_BYTES' failed.`

I have Grid configured with standard MPI comms so by my understanding, these shared buffer allocs for the comms buffers are not needed. However it appears that Stencil.h doesn't check the MPI mode. It would be great if Stencil did a check that Grid is configured to use the hybrid MPI and if not just do regular allocs.

**Comment by paboyle** [comment]
ok, but future release. For now use --shm MB 
to allocate more.

**Comment by paboyle** [comment]
Closing as there is only the single MPI option, and this is compulsory. Too many platforms with multi socket SMP and huge page issues and Device memory etc..
