### ISSUE TITLE
mpi-auto fails on ARCHER

### ISSUE THREAD

**Issue by coppolachan** [paboyle/Grid#71]
the flag `mpi-auto` triggers a failure in the configure step in ARCHER.
The responsible is the 
`LX_FIND_MPI`
which seems unsupported by the Cray wrappers in that machine.
Compilation with just
`--enable-comms=mpi`
works.

Two options
- discard this as a localised problem on ARCHER (but not sure yet)
- address by making the search for mpi flags more portable

**Comment by aportelli** [comment]
Hi Guido,

This is known. When I redid the build system the Cray wrappers were exactly the motivation to include an automatic MPI option and a manual one. The fact that you need to use the manual mode for a Cray machine is also described in the Readme. I view `mpi-auto` as a convenient option but it is not intended to work in all cases. So I don't think it is an issue and would not tag that as a bug. If you think this is too confusing an idea would be to make a more explicit statement in the Readme.

**Comment by coppolachan** [comment]
Understood.
We should put the info in the mpi section, not just in the section for the compilation for KNL. Maybe useful that the error message from the configure states that mpi-auto is not supported in the Cray machine.
I will do this modification.

**Comment by coppolachan** [comment]
Done, closing this
