### ISSUE TITLE
barrier synch model for CG

### ISSUE THREAD

**Issue by paboyle** [paboyle/Grid#76]
I'm finding on a small test I can get a substantive speed up out
of using the BFM style long lived thread with barrier synch.

e.g. Single node 8^4:
 620GF/s -> 910 GF/s on KNL 7210 (SP)
 62GF/s   -> 72 GF/s on BG/Q node (DP)

On 16^4 local volumes on KNL the gain is minimal though.

If we act, this pushes us into a threading nightmare however, with many routines having
to accept multiple threads entering them.

I will think a little about whether the "parallel_for" macro can work around this and the implications,
but if there is no easy common solution we are looking at having to make "DhopThread"
and "Dhop" routines and changing the CG and other solvers to run in thread / barrier mode.

This seems to be mandated by self threading being 1.5x faster than OpenMP for loops.

I'll make the comparison a little more robust though. I'm tempted to not do this even if it means
a little less performance on the sweet spot on BG/Q since the software cost is large and perhaps
we should just accept it.

**Comment by paboyle** [comment]
The bigger problems presently are in the comms phases which I am working on; this is only a 10% effect and will get washed out when comms is included.

.... but please do stop working on Christmas day  :)

Merry Christmas

**Comment by aportelli** [comment]
Ok cool, don't worry I am soon on my way to see the new Star Wars with the family :-)
Merry Christmas to you too

**Comment by paboyle** [comment]
Not going to do this, so closing.
