### ISSUE TITLE
zMobius CG convergence?

### ISSUE THREAD

**Issue by chulwoo1** [paboyle/Grid#78]
Hi,

Would you mind checking  if the zMobius CG converges when omega has imaginary components? I've modified Test_dwf_cg_prec  DomainWallFermionR -> ZMobiusFermionR and it fails to converge. 
In case you are wondering. omega(s) = 0.25 + 0.01 i

**Comment by paboyle** [comment]
Can  you add the new zMobius test please?

**Comment by paboyle** [comment]
This is fixed as far as I know, with confirmation from Christoph. Closing.
