### ISSUE TITLE
Installation structure

### ISSUE THREAD

**Issue by sunpho84** [paboyle/Grid#85]
Hi Guys!

As you know I have been experiencing with Gruido last week.
I am using Grid as an external library, and I had a little pain in making my code able to compile against the "installed" version of Grid. 

I would assume that one is expected to pass to oneself program the flags

`-I$grid_prefix/include -L$grid_prefix/install/lib -lGrid`

 (where $grid_prefix is the prefix passed when configuring Grid) in agreement with typical package folder structure. If then I include Grid.h as per: 

`#include <Grid/Grid.h>`

I get the error:
`$grid_prefix/include/Grid/algorithms/approx/Remez.h:19:20: fatal error: Config.h: No such file or directory
 #include <Config.h>`

in facts, the file Config.h is included in $grid_prefix/include/Grid, which is not in the searched path.

If I pass instead 

`-I$grid_prefix/include/Grid`

and include Grid.h as in: 

`#include <Grid.h>`

 what I obtain is the error:

`$grid_prefix/include/Grid/Grid.h:63:24: fatal error: Grid/Timer.h: No such file or directory
 #include <Grid/Timer.h>`

beacuse now "Grid/" is already parth of the search path. So ultimately I need to compile the code with both paths:

`-I$grid_prefix/include -I$grid_prefix/include/Grid`

Provided that this combination is kept, everything goes fine, but I find this hard intuitive.

Another issue is the fact that, as you distribute Config.h file, the "PACKAGE_NAME", "PACKAGE_STRING"  etc macros clash with those used in my autotools generated header. A typical solution that I've seen used is to wrap the Config.h in a "true" included file, and then rename the package macros. For example c-lime library does the following:

#ifndef LIME_CONFIG_H
#define LIME_CONFIG_H

/* Undef the unwanted from the environment -- eg the compiler command line */
#undef PACKAGE
#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION
#undef VERSION

/* Include the stuff generated by autoconf */
#include "lime_config_internal.h"

/* Prefix everything with LIME_ */
static const char* const LIME_PACKAGE = PACKAGE;
static const char* const LIME_PACKAGE_BUGREPORT = PACKAGE_BUGREPORT;
static const char* const LIME_PACKAGE_NAME = PACKAGE_NAME;
static const char* const LIME_PACKAGE_STRING = PACKAGE_STRING;
static const char* const LIME_PACKAGE_TARNAME = PACKAGE_TARNAME;
static const char* const LIME_PACKAGE_VERSION = PACKAGE_VERSION;
/* LIME_VERSION is already defined in lime_defs.h */

/* Undef the unwanted */
#undef PACKAGE
#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION
#undef VERSION
#endif

**Comment by paboyle** [comment]
Thanks -- Looks like this should be an #include <Grid/Config.h>
and not Config.h.

Peter

**Comment by sunpho84** [comment]
For what concern the other issue, I've created a pull request with simple solution, which prepends all "PACKAGE" with "GRID_", which should do the big part of the work. Another more robust possibility could involve using the [ax_prefix_config_h](https://www.gnu.org/software/autoconf-archive/ax_prefix_config_h.html) macro

**Comment by paboyle** [comment]
Antonin believes the Remez issue was fixed with his work to make install work well with some measurement code he is developing as external.

I'm not sure what to do about PACKAGE and if this is still a problem.
For example, this proposal doesn't REDEFINE the environment back to the original.

I would drop the milestone for this off 0.7.0 as I want to make the release once testing is robust.

We can worry about package macros later (for example, you could wrap these yourself for now).

**Comment by paboyle** [comment]
As hadrons / grid are distinct packages we are now testing install regularly,
