### ISSUE TITLE
Autoconf files

### ISSUE THREAD

**Issue by coppolachan** [paboyle/Grid#9]
This is not an issue - more an information message (I don't know if the github messages attached to the commits get broadcasted to everyone so I write also here)
In the latest commit I added a .gitignore file to ignore autoconf files in the commits, and also the compiled libraries and created makefiles from automake. this would allow contributors to skip reconfiguring the tools and keep their own environment.

For new users, I also added a simple utility called reconfigure_script (maybe should be moved to the scripts dir) that runs all  autotools command to setup the correct environment.

**Comment by sidkashyap** [comment]
I looked at the reconfigure script that calls the series of commands. I guess that is helpful. 

We can discuss the autoconf changes that is planned for the future and I will be more than happy to contribute on those efforts.
