### ISSUE TITLE
Develop doesn't compile

### ISSUE THREAD

**Issue by giltirn** [paboyle/Grid#95]
My compiler is complaining of invalid intrinsic calls in the Grid_avx.h code:

/home/ckelly/CPS/src/grid_gitflow/Grid/include/Grid/simd/Grid_avx.h: In static member function ‘static __m256i Grid::Optimization::PrecisionChange::StoH(__m256, __m256)’:
/home/ckelly/CPS/src/grid_gitflow/Grid/include/Grid/simd/Grid_avx.h:480:36: error: cannot convert ‘__m128i {aka __vector(2) long long int}’ to ‘__m128 {aka __vector(4) float}’ for argument ‘1’ to ‘__m256 _mm256_castps128_ps256(__m128)’
       h = _mm256_castps128_ps256(ha);
                                    ^
/home/ckelly/CPS/src/grid_gitflow/Grid/include/Grid/simd/Grid_avx.h:481:38: error: cannot convert ‘__m128i {aka __vector(2) long long int}’ to ‘__m128 {aka __vector(4) float}’ for argument ‘2’ to ‘__m256 _mm256_insertf128_ps(__m256, __m128, int)’
       h = _mm256_insertf128_ps(h,hb,1);
                                      ^
/home/ckelly/CPS/src/grid_gitflow/Grid/include/Grid/simd/Grid_avx.h:485:14: error: cannot convert ‘__m256 {aka __vector(8) float}’ to ‘__m256i {aka __vector(4) long long int}’ in return
       return h;
              ^
/home/ckelly/CPS/src/grid_gitflow/Grid/include/Grid/simd/Grid_avx.h: In static member function ‘static void Grid::Optimization::PrecisionChange::HtoS(__m256i, __m256&, __m256&)’:
/home/ckelly/CPS/src/grid_gitflow/Grid/include/Grid/simd/Grid_avx.h:489:53: error: cannot convert ‘__m256i {aka __vector(4) long long int}’ to ‘__m256 {aka __vector(8) float}’ for argument ‘1’ to ‘__m128 _mm256_extractf128_ps(__m256, int)’
       sa = _mm256_cvtph_ps(_mm256_extractf128_ps(h,0));
                                                     ^
/home/ckelly/CPS/src/grid_gitflow/Grid/include/Grid/simd/Grid_avx.h:490:53: error: cannot convert ‘__m256i {aka __vector(4) long long int}’ to ‘__m256 {aka __vector(8) float}’ for argument ‘1’ to ‘__m128 _mm256_extractf128_ps(__m256, int)’
       sb = _mm256_cvtph_ps(_mm256_extractf128_ps(h,1));

I have managed to fix all the issues by modifying the code to the following (starting Grid_avx.h:475):

   static inline __m256i StoH (__m256 a,__m256 b) {
      __m256i hi;
#ifdef USE_FP16
      __m256 h;
      __m128i ha = _mm256_cvtps_ph(a,0);
      __m128 hha = _mm_cvtepi32_ps(ha);	      
      __m128i hb = _mm256_cvtps_ph(b,0);
      __m128 hhb = _mm_cvtepi32_ps(hb);	
      h = _mm256_castps128_ps256(hha);
      h = _mm256_insertf128_ps(h,hhb,1);
      hi = _mm256_cvtps_epi32(h);
#else 
      assert(0);
#endif
      return hi;
    }
    static inline void  HtoS (__m256i h,__m256 &sa,__m256 &sb) {
#ifdef USE_FP16
      __m256 hh = _mm256_cvtepi32_ps(h);
      __m128 hh0 = _mm256_extractf128_ps(hh,0);
      __m128i hh0i = _mm_cvtps_epi32(hh0);
      __m128 hh1 = _mm256_extractf128_ps(hh,1);
      __m128i hh1i = _mm_cvtps_epi32(hh1);      
      sa = _mm256_cvtph_ps(hh0i);
      sb = _mm256_cvtph_ps(hh1i);
#else
      assert(0);
#endif

Unfortunately this involves a lot more instructions!

**Comment by paboyle** [comment]
This was already fixed I think with explicit casts?
Which compiler?
Precise error message?
Is it still present?

**Comment by giltirn** [comment]
Can confirm the error appears no longer present in the latest commit.
