### ISSUE TITLE
Test_staggered_block_cg_unprec does not compile in current develop

### ISSUE THREAD

**Issue by coppolachan** [paboyle/Grid#96]
Example of error output   

```
CXX      Test_staggered_block_cg_unprec.o
In file included from ../../../../Grid/tests/solver/Test_staggered_block_cg_unprec.cc:29:
In file included from /home/neo/Codes/Grid/include/Grid/Grid.h:41:
In file included from /home/neo/Codes/Grid/include/Grid/GridCore.h:75:
In file included from /home/neo/Codes/Grid/include/Grid/lattice/Lattice.h:31:
In file included from /home/neo/Codes/Grid/include/Grid/lattice/Lattice_base.h:329:
/home/neo/Codes/Grid/include/Grid/lattice/Lattice_reduction.h:364:34: error: invalid operands to binary expression ('scalar_type' (aka 'complex<float>') and 'RealD'
      (aka 'double'))
      as[l] = scalar_type(a[ldx])*scale;
              ~~~~~~~~~~~~~~~~~~~^~~~~~
/home/neo/Codes/Grid/include/Grid/algorithms/iterative/BlockConjugateGradient.h:299:5: note: in instantiation of function template specialization
      'Grid::sliceMaddVector<Grid::iScalar<Grid::iScalar<Grid::iVector<Grid::Grid_simd<std::complex<float>, __attribute__((__vector_size__(8 * sizeof(float)))) float>, 3>
      > > >' requested here
    sliceMaddVector(Psi,v_alpha, P,Psi,Orthog);     // add alpha *  P to psi
    ^
/home/neo/Codes/Grid/include/Grid/algorithms/iterative/BlockConjugateGradient.h:221:4: note: in instantiation of member function
      'Grid::MultiRHSConjugateGradient<Grid::Lattice<Grid::iScalar<Grid::iScalar<Grid::iVector<Grid::Grid_simd<std::complex<float>, __attribute__((__vector_size__(8 *
      sizeof(float)))) float>, 3> > > > >::operator()' requested here
   MultiRHSConjugateGradient(RealD tol, Integer maxit, bool err_on_no_conv = true)
```

**Comment by paboyle** [comment]
Fixed

**Comment by paboyle** [comment]
Sorry fixed the staggered CG, not block. Reopen. Will get to this

**Comment by paboyle** [comment]
The block cg compiles for me; clang 3.8, macos X

what compiler / O/S are you using and can you confirm that current develop does not compile still?

**Comment by paboyle** [comment]
We believe this is fixed. Closing.

**Comment by erinaldi** [comment]
/nfs/tmp2/rinaldi2/Grid/include/Grid/lattice/Lattice_reduction.h(543): error: no suitable user-defined conversion from "Grid::vComplex" to "vector_typeD" exists
  	vector_typeD rtmp = TensorRemove(tmp);
  	                    ^
          detected during:
            instantiation of "void Grid::sliceInnerProductMatrix(Eigen::MatrixXcd &, const Grid::Lattice<vobj> &, const Grid::Lattice<vobj> &, int) [with vobj=Grid::QCD::vColourVector]" at line 88 of "/nfs/tmp2/rinaldi2/Grid/include/Grid/algorithms/iterative/BlockConjugateGradient.h"
            instantiation of "void Grid::BlockConjugateGradient<Field>::ThinQRfact(Eigen::MatrixXcd &, Eigen::MatrixXcd &, Eigen::MatrixXcd &, Field &, const Field &) [with Field=Grid::Lattice<Grid::QCD::vColourVector>]" at line 202 of "/nfs/tmp2/rinaldi2/Grid/include/Grid/algorithms/iterative/BlockConjugateGradient.h"
            instantiation of "void Grid::BlockConjugateGradient<Field>::BlockCGrQsolve(Grid::LinearOperatorBase<Field> &, const Field &, Field &) [with Field=Grid::Lattice<Grid::QCD::vColourVector>]" at line 115 of "/nfs/tmp2/rinaldi2/Grid/include/Grid/algorithms/iterative/BlockConjugateGradient.h"
            instantiation of "void Grid::BlockConjugateGradient<Field>::operator()(Grid::LinearOperatorBase<Field> &, const Field &, Field &) [with Field=Grid::Lattice<Grid::QCD::vColourVector>]" at line 109 of "../../../../tests/solver/Test_staggered_block_cg_unprec.cc"

compilation aborted for ../../../../tests/solver/Test_staggered_block_cg_unprec.cc (code 2)

-------------------------------
Compiling on Intel Xeon E5-2695v4 Broadwell cluster.
* cat /proc/cpuinfo | grep 'model name' | uniq
model name	: Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz

* Currently Loaded Modules:

  1) texlive/2016   2) StdEnv   3) intel/17.0.2   4) mvapich2/2.2

* (compilation failed with #error thrown by unsupported compiler when using intel/16.0.3 although the Grid github page seems to imply that compiler version should be OK. In any case I use the intel/17.0.2 version)

* ../../configure --enable-precision=single --enable-simd=AVX2 --enable-comms=mpi-auto --with-gmp="libraries/gmp" --with-mpfr="libraries/mpfr" CXX="icpc" MPICXX="mpicc"

--------------
Uploaded configure summary.
[grid.configure.summary.txt](https://github.com/paboyle/Grid/files/1099882/grid.configure.summary.txt)

--------------
Error is related only to `tests`. Everything else compiles with no problem.

**Comment by paboyle** [comment]
I know the fix ; I fixed in a local branch already (feature/dwf-multirhs, where I'm developing
the MPI split features, and will propagate back to develop soon. ) Since it only affects make tests,
I will leave it until it trickles down, rather than patch two different places & resolve conflict.
